apiUrl: ""
annotations: {}
skipCertCheck: false
trustedCAs: ca-cert-bundle
metadataEnrichment:
  enabled: false
oneAgent: {}
activeGate:
  capabilities:
    - routing
    - kubernetes-monitoring
    - metrics-ingest
    - dynatrace-api
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1.5Gi