---
# ClusterRole needed to grant permissions to the service account to write traces and metrics to all tenants
# todo
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tempostack-traces-write
  labels:
{{- include "tempo-stack.labels" . | nindent 4 }}
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      {{ .Values.otelCollector.role.aggregation.clusterRoleName }}: "true"