---
# TESTING apc.namespace.test - change occurence to apc.namespace.type. This is only for testing of the kyverno clusterpolicy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-otelcollector-tenants
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    policies.kyverno.io/title: Update Open Telemetry tenants on namespace create
    policies.kyverno.io/category: gitops
    policies.kyverno.io/subject: Sync Open Telemetry tenants with namespaces
    policies.kyverno.io/minversion: 1.13.0
spec:
  mutateExistingOnPolicyUpdate: false
  rules:
    - name: add-tenant-to-otelcollector
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              namespaces:
                - "kube-*"
                - "kyverno"
                - "openshift-*"
      preconditions:
        all:
          - key: {{`"{{ request.object.metadata.labels.\"apc.namespace.test\" || ''}}"`}}
            operator: Equals
            value: application
      mutate:
        targets:
          - apiVersion: opentelemetry.io/v1beta1
            kind: OpenTelemetryCollector
            name: {{ .Values.instanceNameOverride | default (include "opentelemetry-collector.fullname" .) }}
            namespace: {{ .Release.Namespace }}
        patchStrategicMerge:
          spec:
            config:
              exporters:
                "otlp/{{`{{ request.object.metadata.name }}`}}":
                  endpoint: {{ .Values.tracesEndpoint | required "Traces endpoint is required!" }}
                  auth:
                    authenticator: bearertokenauth
                  headers:
                    X-Scope-OrgID: {{`"{{ request.object.metadata.name }}"`}}
                  tls:
                    insecure: false
                    ca_file: "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt"
              service:
                pipelines:
                  "traces/{{`{{ request.object.metadata.name }}`}}":
                    receivers:
                      - jaeger
                      - otlp
                      - zipkin
                    processors:
                      - memory_limiter
                      - k8sattributes
                      - resourcedetection
                      - batch
                    exporters:
                      - "otlp/{{`{{ request.object.metadata.name }}`}}"