apiVersion: v2
name: logging-helm
description: A Helm chart to configure OpenShift logging infrastructure (LokiStack, ClusterLogForwarder, UIPlugin)
type: application
version: 1.0.0
dependencies:
  - name: apc-global-overrides
    version: 1.6.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
