# Example values for hub01 environment (large LokiStack, no hub forwarding)
lokistack:
  size: 1x.small
  limits:
    global:
      ingestion:
        ingestionRate: 20
        ingestionBurstSize: 40
    retention:
      days: 20

collector:
  resources:
    limits:
      cpu: 8
      memory: 8Gi
    requests:
      cpu: 500m
      memory: 1Gi

hubForwarding:
  enabled: false

externalSecret:
  enabled: false
