apiVersion: v2
name: vector-helm
description: A Helm chart to install Vector log aggregator
version: 1.0.0
appVersion: "0.38.1"

dependencies:
  - name: vector
    version: 0.38.1
    repository: https://helm.vector.dev
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
