global:
  apc:
    environmentShort: h
    cluster:
      baseDomain: hub01.cloud.example.com
    services:
      certManager:
        defaultClusterIssuer: vault-hub-issuer
      externalSecretsOperator:
        defaultClusterSecretStore: vault-hub-secret-store
      vault:
        KVmountPlatform: apc-platform

vectorMetalLB:
  addresses:
    - 192.0.2.100/32

vectorNetworkPolicy:
  syslogUdpCidrs:
    - 192.0.2.0/26
    - 192.0.2.128/25
  syslogTcpCidrs:
    - 192.0.2.0/26
    - 192.0.2.128/25
  webhookCidrs:
    - 198.51.100.0/23
    - 198.51.100.0/23
    - 198.51.100.0/23

vectorSiem:
  endpoint: https://siem.example.com:8088/
