global:
  apc:
    environmentShort: h
    cluster:
      baseDomain: hub01.cloud.socpoist.sk
    services:
      certManager:
        defaultClusterIssuer: vault-hub-issuer
      externalSecretsOperator:
        defaultClusterSecretStore: vault-hub-secret-store
      vault:
        KVmountPlatform: apc-platform

vector:
  role: Agent
  customConfig:
    api:
      enabled: true
      address: 0.0.0.0:8686
      playground: false
    sources:
      internal_metrics:
        type: internal_metrics
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [internal_metrics]
        address: 0.0.0.0:9090
  extraObjects: []
  extraVolumes: []
  extraVolumeMounts: []
  service:
    ports:
      - name: prom-exporter
        protocol: TCP
        port: 9090
        targetPort: 9090
