acm-operatorpolicy:
  subscription:
    channel: stable
    name: smb-csi-driver-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: smb-csi-driver-operator.v4.18.0-202605071100

  upgradeApproval: Automatic
  versions:
    - smb-csi-driver-operator.v4.18.0-202605071100
