apiVersion: v2
name: eck-instance
description: A Helm chart for deploying the ECK instance
type: application
version: 1.0.0
dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
  - name: prometheus-elasticsearch-exporter
    version: 7.2.1
    repository: https://prometheus-community.github.io/helm-charts
