# globals values and their overrides in the chart
# global:
#   apc:
#     cluster:
#       appsDomain:
# overrides
# cluster:
#   appsDomain:

releaseServiceOverride: ArgoCD

elasticsearch:
  route: true
  version: 9.3.1
  nodesCount: 3
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m
  volumeClaim:
    size: 100Gi
    storageClass: ocs-storagecluster-ceph-rbd

kibana:
  route: true
  version: 9.3.1
  nodesCount: 1
  requests:
    memory: 1Gi
    cpu: 500m
  limits:
    memory: 2Gi
    cpu: 1000m

backup:
  enabled: true
  s3storageClass: ocs-storagecluster-ceph-rgw
  backupInitContainer:
    image: quay.io/curl/curl
    tag: 8.18.0
  
prereqs:
  container:
    image: registry.redhat.io/openshift4/ose-cli
    tag: v4.15

defaultSecurityContext:
  runAsUser:
  runAsGroup:
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault


secretStore: vault-hub01
