apiVersion: dynatrace.com/v1beta6
kind: DynaKube
metadata:
  name: {{ include "apc-global-overrides.clusterName" . | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-instance.labels" . | nindent 4 }}
  annotations:
    {{- $annotations := merge (deepCopy (.Values.annotations | default dict)) (dict "feature.dynatrace.com/automatic-kubernetes-api-monitoring-cluster-name" (include "apc-global-overrides.clusterName" $ | default $.Release.Name)) }}
    {{- toYaml $annotations | nindent 4 }}
spec:
  apiUrl: {{ required "apiUrl is required" .Values.apiUrl | quote }}
  skipCertCheck: {{ .Values.skipCertCheck }}
  trustedCAs: {{ .Release.Name }}-trusted-ca
  tokens: {{ .Release.Name }}
  {{- with .Values.metadataEnrichment }}
  metadataEnrichment:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.oneAgent }}
  oneAgent:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.activeGate }}
  activeGate:
    {{- toYaml . | nindent 4 }}
  {{- end }}