apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dynatrace-instance.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ if .Values.externalSecret }}{{ .Values.externalSecret.refreshInterval | default "1h" | quote }}{{ else }}"1h"{{ end }}
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
  data:
    - secretKey: apiToken
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/apc-dynatrace/token
        property: apiToken
    - secretKey: dataIngestToken
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/apc-dynatrace/token
        property: dataIngestToken
