apiVersion: v2
name: metrics-helm
description: A Helm chart to configure OpenShift metrics infrastructure (ClusterMonitoringConfig, UserWorkloadMonitoringConfig, AlertManager via ESO)
type: application
version: 1.0.0

dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
