global:
  apc:
    customer: socpoistsk
    environment: hub
    cluster:
      name: hub01
    proxy: http://proxysp.socpoist.sk:8080
    noProxy: .socpoist.sk,.svc,.cluster.local,localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,172.20.0.1
    proxyCIDRs:
      - 10.1.1.7/32
    services:
      externalSecretsOperator:
        defaultClusterSecretStore: apc

clusterMonitoring:
  managedClusterUUID: "8cc9d698-a038-40c7-83db-a25552868189"
  location: primary
  prometheus:
    retention: "7d"
    storageSize: "60Gi"
    storageClassName: ocs-storagecluster-ceph-rbd
  alertmanager:
    storageSize: "1Gi"
    storageClassName: ocs-storagecluster-ceph-rbd

userWorkloadMonitoring:
  enabled: true
  prometheus:
    retention: "7d"
    storageSize: "24Gi"
    storageClassName: ocs-storagecluster-ceph-rbd
    remoteWrite:
      enabled: true
      secretName: telemetry-remote-write
      url: https://infogw.api.openshift.com/metrics/v1/receive
      writeRelabelConfigs:
        - action: keep
          sourceLabels:
            - __name__
          regex: (cluster_version|cluster_operator_up|ALERTS)
  thanosRuler:
    storageSize: "1Gi"
    storageClassName: ocs-storagecluster-ceph-rbd

alertmanager:
  eso:
    enabled: true
    refreshInterval: "15m"
    vault:
      msteamsKey: socpoist/msteams
      msteamsProperty: hub_url
      healthchecksKey: socpoist/healthchecks.io
      healthchecksProperty: hub_url
      opsgenieKey: socpoist/jira
      opsgenieProperty: hub01_api_key

alertmanagerUWM:
  enabled: true
  eso:
    enabled: true
    refreshInterval: "15m"
    vault:
      msteamsKey: socpoist/msteams
      msteamsProperty: hub_uwm_url
      healthchecksKey: socpoist/healthchecks.io
      healthchecksProperty: hub_uwm_url
      opsgenieKey: socpoist/jira
      opsgenieProperty: hub01_uwm_api_key

hub:
  enabled: true
  alertmanager:
    eso:
      vault:
        opsgenieKey: socpoist/jira
        opsgenieAcsProperty: hub01_api_key_acs
        opsgenieLogsProperty: hub01_api_key_logs

networkPolicy:
  enabled: true
