apiVersion: v2
name: openshift-distributed-tracing
description: A Helm chart for installing Red Hat OpenShift distributed tracing platform (Tempo)
type: application
version: 1.0.0
appVersion: "v0.15"
kubeVersion: '>=1.16-0'
dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/