# OperatorPolicy Values
acm-operatorpolicy:
  subscription:
    channel: stable
    name: tempo-product
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: tempo-operator.v0.15.3-1
  versions:
    - tempo-operator.v0.15.3-1
    - tempo-operator.v0.15.4-1

uiPlugin:
  name: distributed-tracing
  type: DistributedTracing
