apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kyverno-policy-results
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: kyverno.rules
      rules:
        - alert: KyvernoPolicyResultsError
          expr: sum by (policy_name) (increase(kyverno_policy_results_total{rule_result="error"}[2h])) > 0
          for: 10m
          labels:
            severity: warning
            vendor: aspecta
            team: platform
          annotations:
            summary: Kyverno policy:{{ `{{ $labels.policy_name }}` }} run with errors.
            description: Kyverno policy {{ `{{ $labels.policy_name }}` }} run with errors, please investigate kyverno logs for root cause.
        - alert: KyvernoPolicyResultsFail
          expr: sum by (policy_name) (increase(kyverno_policy_results_total{rule_result="fail"}[2h])) > 0
          for: 10m
          labels:
            severity: warning
            vendor: aspecta
            team: platform
          annotations:
            summary: Kyverno policy {{ `{{ $labels.policy_name }}` }} failed.
            description: Kyverno policy {{ `{{ $labels.policy_name }}` }} failed, please investigate kyverno logs for root cause.
        - alert: KyvernoBackgroundControllerDown
          expr: absent(up{job=~".*kyverno-background-controller.*"}) == 1
          for: 10m
          labels:
            severity: warning
            vendor: aspecta
            team: platform
          annotations:
            summary: Kyverno background controller is down.
            description: Kyverno background controller is not running. This controller is responsible for generating resources (e.g. PrometheusRules) for existing namespaces. New and existing namespaces may be missing monitoring alerts.
        - alert: KyvernoAdmissionControllerDown
          expr: absent(up{service="kyverno-svc-metrics",namespace="apc-kyverno"}) == 1
          for: 10m
          labels:
            severity: warning
            vendor: aspecta
            team: platform
          annotations:
            summary: Kyverno admission controller is down.
            description: Kyverno admission controller is not running. This controller is responsible for generating resources (e.g. PrometheusRules) when new namespaces are created. New namespaces will not receive monitoring alerts.