apiVersion: apiextensions.crossplane.io/v1beta1
kind: EnvironmentConfig
metadata:
  name: apc-mettalb-ip-range
data:
  addressRanges:
    {
      "range":
        {
          "start": "10.0.0.1",
          "end": "10.0.0.254",
        }
    }