fullnameOverride: otel-collector
instanceNameOverride: apc-opentelemetry-collector
logsEndpoint: https://lokistack-gateway-http.openshift-logging.svc.cluster.local:8080/api/logs/v1/application/otlp
metricsEndpoint: 0.0.0.0:8889
tracesEndpoint: tempo-apc-tempo-stack-gateway.apc-observability.svc.cluster.local:8090