# otlp exporters (mandatory variables)
logsEndpoint: logs.svc # Logs endpoint - i.e. loki gateway svc
metricsEndpoint: metrics.svc # Metrics endpoint - i.e. prometheus svc
tracesEndpoint: traces.svc # Traces endpoint - i.e. tempo svc

OpenTelemetryCollector:
  # Overrides the default OpenTelemetryCollector configuration
  image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s:0.152.0