apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "ingress-configuration.ingressCertSecretName" . }}
  namespace: openshift-ingress
  labels:
    {{- include "ingress-configuration.labels" . | nindent 4 }}
spec:
  secretName: {{ include "ingress-configuration.ingressCertSecretName" . }}
  issuerRef: 
    kind: ClusterIssuer
    name: {{ include "apc-global-overrides.require-certManagerDefaultClusterIssuer" . }}
  commonName: {{ include "ingress-configuration.ingressCertCommonName" . }}
  dnsNames:
  {{- range include "ingress-configuration.ingressCertDnsNames" . | fromJsonArray }}
    - "{{ . }}"
  {{- end }}
