{{- $env := include "apc-global-overrides.environmentShort" . }}
{{- $vaultStore := "" }}
{{- if .Values.mirror.enabled }}
  {{ $vaultStore = .Values.mirror.upstreamComponent }}
{{- else }}
  {{ $vaultStore = .Release.Namespace }}
{{- end }}

{{- range $user := .Values.kafkaUsers.users }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $user.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  target:
    name: {{ $user.name }}-eso
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $env }}/{{ $vaultStore }}/{{ $user.name }}
      metadataPolicy: None
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" $ }}
---
{{- end }}
