{{- if and .Values.mirror.enabled (not .Values.mirror.primary) }}
{{- $env := include "apc-global-overrides.environmentShort" . }}

{{- range $user := .Values.kafkaUsers.users }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $user.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" $ | nindent 4 }}
spec:
  refreshInterval: 1h
  target:
    name: {{ $user.name }}
    creationPolicy: Orphan
    deletionPolicy: Retain
  dataFrom:
  - extract:
      conversionStrategy: Default
      decodingStrategy: None
      key: {{ $env }}/{{ required "mirror.primaryKafka must be set when mirror.enabled=true and mirror.primary=false" $.Values.mirror.primaryKafka }}/{{ $user.name }}
      metadataPolicy: None
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-hub-secret-store
---
{{- end }}
{{- end }}
