apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ .Release.Name }}-pwd-gen
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" . | nindent 4 }}
spec:
  length: 20
  digits: 5
  symbols: 0
  noUpper: false
  allowRepeat: false
---
