{{- $env := include "apc-global-overrides.environmentShort" . }}
{{- $vaultStore := "" }}
{{- if .Values.mirror.enabled }}
  {{ $vaultStore = .Values.mirror.upstreamComponent }}
{{- else }}
  {{ $vaultStore = .Release.Namespace }}
{{- end }}

{{- range $user := .Values.kafkaUsers.users }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $user.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka.labels" $ | nindent 4 }}
spec:
  updatePolicy: IfNotExists
  refreshInterval: 1h
  secretStoreRefs:
    - name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" $ }}
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: {{ $.Release.Name }}-pwd-gen
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: {{ $env }}/{{ $vaultStore }}/{{ $user.name }}
---
{{- end }}
