{{- if and .Values.mirror.enabled .Values.mirror.primary }}
{{- $env := include "apc-global-overrides.environmentShort" . }}

{{- range $user := .Values.kafkaUsers.users }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $user.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  updatePolicy: Replace
  refreshInterval: 1h
  secretStoreRefs:
    - name: vault-hub-secret-store
      kind: ClusterSecretStore
  selector:
    secret:
      name: {{ $user.name }}
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: {{ $env }}/{{ $.Release.Namespace }}/{{ $user.name }}
---
{{- end }}
{{- end }}
