{{- $env := include "apc-global-overrides.environmentShort" . }}

{{- range $user := .Values.kafkaUsers.users }}
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ $user.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  updatePolicy: IfNotExists
  refreshInterval: 1h
  secretStoreRefs:
    - name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" $ }}
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: {{ $.Release.Name }}-pwd-gen
  data:
    - conversionStrategy: None
      match:
        remoteRef:
          remoteKey: {{ $env }}/{{ $.Values.mirror.upstreamComponent }}/{{ $user.name }}
---
{{- end }}
