{{- if .Values.namespaces.coo.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operators.coo.namespace }}
  labels:
    {{- include "logging-operators.labels" . | nindent 4 }}
    apc.namespace.type: platform
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
{{- end }}
