{{- if .Values.operators.coo.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-observability-operator
  namespace: {{ .Values.operators.coo.namespace }}
  labels:
    {{- include "logging-operators.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  channel: {{ .Values.operators.coo.channel | quote }}
  installPlanApproval: {{ .Values.operators.coo.installPlanApproval | quote }}
  name: cluster-observability-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.operators.coo.csv | quote }}
{{- end }}
