{{- if .Values.operators.logging.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cluster-logging
  namespace: {{ .Values.operators.logging.namespace }}
  labels:
    {{- include "logging-operators.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-40"
spec:
  channel: {{ .Values.operators.logging.channel | quote }}
  installPlanApproval: {{ .Values.operators.logging.installPlanApproval | quote }}
  name: cluster-logging
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: {{ .Values.operators.logging.csv | quote }}
{{- end }}
