apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "apps-centralne-komponenty-bpm.fullname" . }}-project-operator
  labels:
    rbac.authorization.k8s.io/aggregate-to-apc-project-operator: "true"
    {{- include "apps-centralne-komponenty-bpm.labels" . | nindent 4 }}
rules:
- apiGroups:
  - bpm.ck.socpoist.sk
  resources:
  - microservices
  verbs:
  - "*"
- apiGroups:
  - bpm.ck.socpoist.sk
  resources:
  - microserviceaccess
  verbs:
  - "*"
