# OperatorPolicy Values
acm-operatorpolicy:
  subscription:
    channel: stable
    name: opentelemetry-product
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: opentelemetry-operator.v0.144.0-3
  versions:
    - opentelemetry-operator.v0.144.0-3
