
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cluster-policy-application
  labels:
    {{- include "user-workload-monitoring-policy.labels" . | nindent 4 }}
spec:
  generateExisting: true
  rules:
  - name: generate-prometheus-rules-application
    skipBackgroundRequests: true
    match:
      any:
      - resources:
          kinds: [Namespace]
          selector:
            matchExpressions:
            - key: apc.namespace.type
              operator: In
              values: ["application"]
      - resources:
          kinds: [Namespace]
          selector:
            matchExpressions:
            - key: apc.project.group
              operator: Exists
    exclude:
      any:
      - resources:
          kinds: [Namespace]
          names: ["openshift*", "kube*", "default"]
      - resources:
          kinds: [Namespace]
          selector:
            matchExpressions:
            - key: openshift.io/cluster-monitoring
              operator: In
              values: ["true", ""]
      - resources:
          kinds: [Namespace]
          selector:
            matchExpressions:
            - key: openshift.io/user-monitoring
              operator: In
              values: ["false"]
    generate:
      synchronize: true
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      name: "user-workload-monitoring-app-{{`{{request.object.metadata.name}}`}}"
      namespace: "{{`{{request.object.metadata.name}}`}}"
      data:
        spec:
          groups:
          - name: "user-workload-app{{`{{request.object.metadata.name}}`}}"
            rules:
              {{- include "monitoring-prometheusrules.rulesApp" . | nindent 14 }}
