apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatling-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatling-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gatling-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gatling-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gatling-operator.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=0.0.0.0:8080
          - --leader-elect
          - --max-concurrent-reconciles=1
          command:
            - /manager
          name: manager
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
