apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gatling-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatling-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount | default 1}}
  selector:
    matchLabels:
      {{- include "gatling-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gatling-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- $servingCertSecretName := default (printf "%s-tls" (include "gatling-operator.fullname" .)) .Values.serviceMonitor.openshift.serviceCA.servingCertSecretName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gatling-operator.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - args:
          - --secure-listen-address=0.0.0.0:8443
          - --upstream=http://127.0.0.1:8080/
          - --logtostderr=true
          - --v=2
          {{- if .Values.serviceMonitor.openshift.serviceCA.enabled }}
          - --tls-cert-file=/etc/tls/private/tls.crt
          - --tls-private-key-file=/etc/tls/private/tls.key
          {{- end }}
          image: ghcr.io/kube-rbac-proxy/kube-rbac-proxy:v0.22.1
          name: kube-rbac-proxy
          {{- with .Values.kubeRbacProxy.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.serviceMonitor.openshift.serviceCA.enabled }}
          volumeMounts:
          - mountPath: /etc/tls/private
            name: service-tls
            readOnly: true
          {{- end }}
          ports:
          - containerPort: 8443
            name: https
          {{- with .Values.kubeRbacProxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          - --max-concurrent-reconciles=1
          command:
            - /manager
          name: manager
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if or .Values.volumes .Values.serviceMonitor.openshift.serviceCA.enabled }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.serviceMonitor.openshift.serviceCA.enabled }}
        - name: service-tls
          secret:
            secretName: {{ $servingCertSecretName }}
        {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
