{{- if and .Values.serviceMonitor.enabled .Values.serviceMonitor.openshift.serviceCA.enabled }}
{{- $caBundleConfigMapName := default (printf "%s-serving-certs-ca-bundle" (include "gatling-operator.fullname" .)) .Values.serviceMonitor.openshift.serviceCA.caBundleConfigMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $caBundleConfigMapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatling-operator.labels" . | nindent 4 }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
{{- end }}
