{{- if .Values.serviceMonitor.enabled }}
{{- $fullName := include "gatling-operator.fullname" . }}
{{- $caBundleConfigMapName := default (printf "%s-serving-certs-ca-bundle" $fullName) .Values.serviceMonitor.openshift.serviceCA.caBundleConfigMapName }}
{{- $serverName := default (printf "%s.%s.svc" $fullName .Release.Namespace) .Values.serviceMonitor.tlsConfig.serverName }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatling-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "gatling-operator.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: {{ .Values.serviceMonitor.port }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      scheme: {{ .Values.serviceMonitor.scheme }}
      {{- if .Values.serviceMonitor.openshift.serviceCA.enabled }}
      tlsConfig:
        ca:
          configMap:
            name: {{ $caBundleConfigMapName }}
            key: {{ .Values.serviceMonitor.openshift.serviceCA.caBundleConfigMapKey }}
        serverName: {{ $serverName }}
      {{- else }}
      tlsConfig:
        {{- toYaml .Values.serviceMonitor.tlsConfig | nindent 8 }}
      {{- end }}
{{- end }}
