---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "etcd-hcp-backup.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "etcd-hcp-backup.labels" . | nindent 4 }}
