{{- if and (eq (include "apc-global-overrides.clusterIsHub" .) "true") (.Values.alertmanagerConfig.enabled) }}
{{- $proxy := include "apc-global-overrides.proxy" . | trim }}
{{- $noProxy := include "apc-global-overrides.noProxy" . | trim }}
{{- $webhookUrl := .Values.alertmanagerConfig.webhookUrl | required "alertmanagerConfig.webhookUrl is required" }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "multi-cluster-observability.labels" . | nindent 4 }}
type: Opaque
stringData:
  alertmanager.yaml: |
    "global":
      "resolve_timeout": "5m"
    "receivers":
    - name: "null"
    - name: "teams_aspecta"
      msteams_configs:
        - send_resolved: true
{{- if $proxy }}
          http_config:
            proxy_url: {{ $proxy }}
{{- if $noProxy }}
            no_proxy: {{ $noProxy }}
{{- end }}
{{- end }}
          webhook_url: {{ $webhookUrl }}
    "route":
      "group_by": ['alertname', 'cluster', 'service']
      "group_wait": "30s"
      "group_interval": "5m"
      "receiver": "teams_aspecta"
      "repeat_interval": "12h"
      "routes":
      - "matchers":
        - "severity = warning"
        "receiver": "teams_aspecta"
      - "matchers":
        - "severity = critical"
        "receiver": "teams_aspecta"
      - "receiver": "null"
        "matchers":
        - alertname = Watchdog
      - "receiver": "null"
        "matchers":
        - severity =~ "info|none"
{{- end }}
