{{- if and .Values.metricsAllowlists.enabled .Values.metricsAllowlists.configMaps }}
{{- range $cm := .Values.metricsAllowlists.configMaps }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $cm.name }}
  namespace: {{ $cm.namespace }}
  labels:
    {{- include "multi-cluster-observability.labels" $ | nindent 4 }}
data:
  {{ $cm.dataKey }}: |
    names:
{{- range $name := $cm.names }}
      - {{ $name }}
{{- end }}
{{- end }}
{{- end }}
