{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
  labels:
    {{- include "multi-cluster-observability.labels" . | nindent 4 }}
  annotations:
    mco-disable-alerting: "true"
spec:
  observabilityAddonSpec:
    interval: 30
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
      tlsSecretMountPath: /etc/ssl/certs/thanos
      tlsSecretName: thanos-tls-ca
  advanced:
    retentionConfig:
      blockDuration: 2h
      deleteDelay: 48h
      retentionInLocal: 24h
      retentionResolutionRaw: 35d
      retentionResolution5m: 45d
      retentionResolution1h: 90d
{{- end }}
