{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ .Values.bucketSecretPolicy.name }}
  namespace: {{ .Values.bucketSecretPolicy.namespace }}
  labels:
    {{- include "multi-cluster-observability.labels" . | nindent 4 }}
  {{- with .Values.bucketSecretPolicy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  background: true
  rules:
    - name: obc
      match:
        all:
          - resources:
              kinds:
                - ObjectBucketClaim
      context:
        - name: obcsecret
          apiCall:
            urlPath: "/api/v1/namespaces/{{`{{request.object.metadata.namespace}}`}}/secrets/{{`{{request.object.metadata.name}}`}}"
            default: '{}'
        - name: obcconfigmap
          apiCall:
            urlPath: "/api/v1/namespaces/{{`{{request.object.metadata.namespace}}`}}/configmaps/{{`{{request.object.metadata.name}}`}}"
            default: '{}'
      preconditions:
        all:
          - key: "{{`{{ obcsecret }} | length(keys(@))`}}"
            operator: NotEquals
            value: "0"
          - key: "{{`{{ obcconfigmap }} | length(keys(@))`}}"
            operator: NotEquals
            value: "0"
      generate:
        generateExisting: true
        synchronize: true
        orphanDownstreamOnPolicyDelete: true
        apiVersion: v1
        kind: Secret
        name: "{{`{{ request.object.metadata.name }}`}}-secretinfo"
        namespace: "{{ .Values.bucketSecretPolicy.targetNamespace }}"
        data:
          stringData:
            thanos.yaml: |
              type: s3
              config:
                bucket: {{`{{ obcconfigmap.data.BUCKET_NAME }}`}}
                endpoint: {{`{{ obcconfigmap.data.BUCKET_HOST }}`}}:{{`{{ obcconfigmap.data.BUCKET_PORT }}`}}
                insecure: false
                access_key: {{`{{ obcsecret.data.AWS_ACCESS_KEY_ID }}`}}
                secret_key: {{`{{ obcsecret.data.AWS_SECRET_ACCESS_KEY }}`}}
                http_config:
                  tls_config:
                    insecure_skip_verify: false
                    ca_file: {{ .Values.bucketSecretPolicy.thanosCaFile }}
{{- end }}
