{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: acm-thanos-rgw
  namespace: open-cluster-management-observability
  labels:
    {{- include "multi-cluster-observability.labels" . | nindent 4 }}
spec:
  storageClassName: ocs-storagecluster-ceph-rgw
  generateBucketName: acm-thanos-rgw
{{- end }}
