{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: generate-thanos-object-storage-secret
  namespace: open-cluster-management-observability
  labels:
    {{- include "multi-cluster-observability.labels" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Generate Thanos Object Storage Secret
    policies.kyverno.io/category: ODF
    policies.kyverno.io/subject: Thanos Object Storage
    policies.kyverno.io/minversion: 1.13.0
spec:
  background: true
  rules:
    - name: thanos-object-storage
      match:
        all:
          - resources:
              kinds:
                - ObjectBucketClaim
      context:
        - name: obcsecret
          apiCall:
            urlPath: "/api/v1/namespaces/{{`{{request.object.metadata.namespace}}`}}/secrets/{{`{{request.object.metadata.name}}`}}"
            default: '{}'
        - name: obcconfigmap
          apiCall:
            urlPath: "/api/v1/namespaces/{{`{{request.object.metadata.namespace}}`}}/configmaps/{{`{{request.object.metadata.name}}`}}"
            default: '{}'
      preconditions:
        all:
          - key: "{{`{{ obcsecret }} | length(keys(@))`}}"
            operator: NotEquals
            value: "0"
          - key: "{{`{{ obcconfigmap }} | length(keys(@))`}}"
            operator: NotEquals
            value: "0"
          - key: "{{`{{ request.object.metadata.deletionTimestamp || '' }}`}}"
            operator: Equals
            value: ""
      skipBackgroundRequests: true
      generate:
        generateExisting: true
        synchronize: true
        orphanDownstreamOnPolicyDelete: true
        apiVersion: v1
        kind: Secret
        name: "thanos-object-storage"
        namespace: "open-cluster-management-observability"
        data:
          metadata:
            labels:
              {{- include "multi-cluster-observability.labels" . | nindent 14 }}
          type: Opaque
          stringData:
            thanos.yaml: |
              type: s3
              config:
                bucket: {{`{{ obcconfigmap.data.BUCKET_NAME }}`}}
                endpoint: {{`{{ obcconfigmap.data.BUCKET_HOST }}`}}:{{`{{ obcconfigmap.data.BUCKET_PORT }}`}}
                insecure: false
                access_key: "{{ "{{" }} base64_decode(obcsecret.data.AWS_ACCESS_KEY_ID || '') {{ "}}" }}"
                secret_key: "{{ "{{" }} base64_decode(obcsecret.data.AWS_SECRET_ACCESS_KEY || '') {{ "}}" }}"
                http_config:
                  tls_config:
                    insecure_skip_verify: false
                    ca_file: /etc/ssl/certs/thanos/service-ca.crt
{{- end }}
