## uses following global values => do not set here
# global:
#   apc:
#     cluster:
#       name:
## and their local overrides
# cluster.name:

releaseServiceOverride: ArgoCD
priorityClassValue: 1000000
ipAddrPool:
  hub: {}

metallbInterface: br-ex
