# # example values as the main configuration is done via the component configuration

# ResourceQuota:
#   eds:
#     default-resource-quota:
#       "count/cronjobs.batch": "20"
#       "count/daemonsets.apps": "0"
#       "count/deployments.apps": "10"
#       "count/ingresses.networking.k8s.io": "10"
#       "count/routes.route.openshift.io": "10"
#       "count/jobs.batch": "50"
#       "count/networkpolicies.networking.k8s.io": "20"
#       "count/replicasets.apps": "100"
#       "count/serviceaccounts": "20"
#       "count/services": "20"
#       "count/statefulsets.apps": "5"
#       "requests.cpu": "4"
#       "requests.memory": "20Gi"
#       "limits.cpu": "8"
#       "limits.memory": "35Gi"
#       "pods": "30"
#       "persistentvolumeclaims": "15"
#       "requests.storage": "300Gi"
#       "services.loadbalancers": "2"
#     cnpg-custom-resource-quota:
#       "count/clusters.postgresql.cnpg.io": "1"
#       "count/backups.postgresql.cnpg.io": "15"
#       "count/scheduledbackups.postgresql.cnpg.io": "2"
#     monitoring-quota:
#       "count/alertmanagerconfigs.monitoring.coreos.com": "1"
#       "count/alertmanagers.monitoring.coreos.com": "0"
#       "count/podmonitors.monitoring.coreos.com": "20"
#       "count/probes.monitoring.coreos.com": "10"
#       "count/prometheuses.monitoring.coreos.com": "0"
#       "count/prometheusrules.monitoring.coreos.com": "10"
#       "count/servicemonitors.monitoring.coreos.com": "20"
#       "count/thanosrulers.monitoring.coreos.com": "0"
#     grafana-quota:
#       "count/alertingrules.loki.grafana.com": "0"
#       "count/grafanaalertrulegroups.grafana.integreatly.org": "0"
#       "count/grafanacontactpoints.grafana.integreatly.org": "0"
#       "count/grafanadashboards.grafana.integreatly.org": "10"
#       "count/grafanadatasources.grafana.integreatly.org": "5"
#       "count/grafanafolders.grafana.integreatly.org": "10"
#       "count/grafananotificationpolicies.grafana.integreatly.org": "0"
#       "count/grafanas.grafana.integreatly.org": "1"
#       "count/lokistacks.loki.grafana.com": "0"
#       "count/recordingrules.loki.grafana.com": "0"
#       "count/rulerconfigs.loki.grafana.com": "0"
#     kubevirt-cr-quota:
#       "count/aaqs.aaq.kubevirt.io": "0"
#       "count/cdiconfigs.cdi.kubevirt.io": "0"
#       "count/cdis.cdi.kubevirt.io": "0"
#       "count/dataimportcrons.cdi.kubevirt.io": "10"
#       "count/datasources.cdi.kubevirt.io": "5"
#       "count/datavolumes.cdi.kubevirt.io": "5"
#       "count/hostpathprovisioners.hostpathprovisioner.kubevirt.io": "0"
#       "count/hyperconvergeds.hco.kubevirt.io": "0"
#       "count/kubevirts.kubevirt.io": "0"
#       "count/migrationpolicies.migrations.kubevirt.io": "0"
#       "count/mtqs.mtq.kubevirt.io": "0"
#       "count/networkaddonsconfigs.networkaddonsoperator.network.kubevirt.io": "0"
#       "count/objecttransfers.cdi.kubevirt.io": "0"
#       "count/openstackvolumepopulators.forklift.cdi.kubevirt.io": "0"
#       "count/ovirtvolumepopulators.forklift.cdi.kubevirt.io": "0"
#       "count/ssps.ssp.kubevirt.io": "0"
#       "count/storageprofiles.cdi.kubevirt.io": "0"
#       "count/virtualmachineclones.clone.kubevirt.io": "2"
#       "count/virtualmachineclusterinstancetypes.instancetype.kubevirt.io": "0"
#       "count/virtualmachineclusterpreferences.instancetype.kubevirt.io": "0"
#       "count/virtualmachineexports.export.kubevirt.io": "2"
#       "count/virtualmachineinstancemigrations.kubevirt.io": "5"
#       "count/virtualmachineinstancepresets.kubevirt.io": "2"
#       "count/virtualmachineinstancereplicasets.kubevirt.io": "2"
#       "count/virtualmachineinstances.kubevirt.io": "2"
#       "count/virtualmachineinstancetypes.instancetype.kubevirt.io": "2"
#       "count/virtualmachinepools.pool.kubevirt.io": "2"
#       "count/virtualmachinepreferences.instancetype.kubevirt.io": "2"
#       "count/virtualmachinerestores.snapshot.kubevirt.io": "5"
#       "count/virtualmachines.kubevirt.io": "2"
#       "count/virtualmachinesnapshotcontents.snapshot.kubevirt.io": "10"
#       "count/virtualmachinesnapshots.snapshot.kubevirt.io": "10"
#       "count/volumeclonesources.cdi.kubevirt.io": "5"
#       "count/volumeimportsources.cdi.kubevirt.io": "5"
#       "count/volumeuploadsources.cdi.kubevirt.io": "5"

# LimitRange:
#   eds:
#     default-limit-range:
#       defaultLimits:
#         "cpu": "200m"
#         "ephemeral-storage": "1Gi"
#         "memory": "200Mi"
#       defaultRequests:
#         "cpu": "50m"
#         "memory": "50Mi"
