{{- range .Values.identityProviders }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: idp-{{ include "apc-global-overrides.require-keycloakRealm" $ | lower }}-{{ .name }}-credentials
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "keycloak.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" $ }}
    kind: ClusterSecretStore
  target:
    name: idp-{{ include "apc-global-overrides.require-keycloakRealm" $ | lower }}-{{ .name }}-credentials
    creationPolicy: Owner
    template:
      data:
        "client-id": "{{`{{ .client-id }}`}}"
        "client-secret": "{{`{{ .client-secret }}`}}"
  data:
  - secretKey: client-id
    remoteRef:
      key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" $ }}/{{ include "apc-global-overrides.require-environmentShort" $ }}/keycloak/{{ include "apc-global-overrides.require-keycloakRealm" $ }}/identity-providers/{{ .name }}/credentials
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" $ }}/{{ include "apc-global-overrides.require-environmentShort" $ }}/keycloak/{{ include "apc-global-overrides.require-keycloakRealm" $ }}/identity-providers/{{ .name }}/credentials
      property: client-secret
---
{{- end }}
