acm-operatorpolicy:
  operatorGroup:
    name: cluster-logging-operator
    namespace: openshift-logging
    targetNamespaces:
    - openshift-logging

  subscription:
    channel: stable-6.1
    name: cluster-logging
    namespace: openshift-logging
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cluster-logging.v6.1.4

  upgradeApproval: Automatic
  versions:
    - cluster-logging.v6.1.4
