acm-operatorpolicy:
  operatorGroup:
    name: cluster-logging-operator
    namespace: openshift-cluster-logging-operator
    targetNamespaces:
    - openshift-cluster-logging-operator

  subscription:
    channel: stable-6.1
    name: cluster-logging
    namespace: openshift-cluster-logging-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cluster-logging.v6.1.4

  upgradeApproval: None
  versions: []
