acm-operatorpolicy:
  subscription:
    channel: stable-6.4
    name: cluster-logging
    namespace: openshift-logging
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cluster-logging.v6.4.6

  upgradeApproval: Automatic
  versions:
    - cluster-logging.v6.2.12
    - cluster-logging.v6.3.4
    - cluster-logging.v6.4.6
