veeam:
  enabled: true
  serviceAccountName: veeam-sa

prometheus-pushgateway:
  persistentVolume:
    enabled: true

  extraArgs:
    - '--web.enable-admin-api'

  serviceAccount:
    create: false
    name: pushgw-sa

  serviceMonitor:
    enabled: true
    namespace: openshift-monitoring

  extraContainers:
    - name: oauth-proxy
      image: registry.redhat.io/openshift4/ose-oauth-proxy:v4.16.0
      args:
        - '--https-address=:9092'
        - '--provider=openshift'
        - '--openshift-service-account=pushgw-sa'
        - >-
          --openshift-delegate-urls={"/":{"group":"monitoring.coreos.com","resource":"prometheuses","verb":"get"}}
        - '--upstream=http://localhost:9091'
        - '--tls-cert=/etc/tls/private/tls.crt'
        - '--tls-key=/etc/tls/private/tls.key'
        - '--cookie-secret-file=/etc/proxy/secrets/cookie-secret'
      ports:
        - containerPort: 9092
          name: public
      volumeMounts:
        - name: prometheus-pushgateway-tls
          mountPath: /etc/tls/private
        - name: pushgateway-cookie-secret
          mountPath: /etc/proxy/secrets
          readOnly: true
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        capabilities:
          drop: ["ALL"]
        seccompProfile:
          type: RuntimeDefault

  extraVolumes:
    - name: prometheus-pushgateway-tls
      secret:
        secretName: prometheus-pushgateway-tls
    - name: pushgateway-cookie-secret
      secret:
        secretName: pushgateway-oauth-cookie-secret
