apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    apc.namespace.type: platform
    openshift.io/cluster-monitoring: "true"
    {{- include "netobserv-config.labels" . | nindent 4 }}
