apiVersion: v2
name: veeam-exporter
description: A Helm chart for Veeam Backup monitoring Grafana dashboard and Windows exporter reference files
type: application
version: 1.0.0
appVersion: "12"
sources:
  - https://github.com/DoTheEvo/veeam-prometheus-grafana
