apiVersion: v2
name: veeam-exporter
description: A Helm chart for Veeam Backup monitoring Grafana dashboard and alert rules
type: application
version: 1.0.0
sources:
  - https://github.com/gr8it/veeam-prometheus-exporter
dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
