{{- if .Values.alertmanager.eso.enabled }}
{{- $am := .Values.alertmanager.eso }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-uwm-receivers
  namespace: openshift-user-workload-monitoring
  labels:
    {{- include "user-workload-monitoring.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ $am.refreshInterval | quote }}
  target:
    name: alertmanager-uwm-receivers
    creationPolicy: Owner
  data:
  - secretKey: msteams_url
    remoteRef:
      key: {{ required "alertmanager.eso.vault.msteamsKey is required" $am.vault.msteamsKey }}
      property: {{ required "alertmanager.eso.vault.msteamsProperty is required" $am.vault.msteamsProperty }}
  - secretKey: healthchecks_url
    remoteRef:
      key: {{ required "alertmanager.eso.vault.healthchecksKey is required" $am.vault.healthchecksKey }}
      property: {{ required "alertmanager.eso.vault.healthchecksProperty is required" $am.vault.healthchecksProperty }}
  - secretKey: opsgenie_key
    remoteRef:
      key: {{ required "alertmanager.eso.vault.opsgenieKey is required" $am.vault.opsgenieKey }}
      property: {{ required "alertmanager.eso.vault.opsgenieProperty is required" $am.vault.opsgenieProperty }}
{{- end }}
