{{- if .Values.alertmanager.eso.enabled }}
{{- $am := .Values.alertmanager.eso }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-uwm-receivers
  namespace: openshift-user-workload-monitoring
  labels:
    {{- include "user-workload-monitoring.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ $am.refreshInterval | quote }}
  target:
    name: alertmanager-uwm-receivers
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ required "alertmanager.eso.vault.secretPath is required" $am.vault.secretPath }}
{{- end }}
