apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-kb-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-instance.labels" . | nindent 4 }}
spec:
  duration: 8760h
  secretName: {{ .Release.Name }}-kb-tls
  dnsNames:
    - {{ .Release.Name }}-kb-http.{{ .Release.Namespace }}.svc
    - {{ .Release.Name }}-kb-http.{{ .Release.Namespace }}.svc.cluster.local
    - {{ .Release.Name }}-kb-{{ .Release.Namespace }}.{{ include "apc-global-overrides.clusterAppsDomain" . }}
  commonName: {{ .Release.Name }}-kb-{{ .Release.Namespace }}.{{ include "apc-global-overrides.clusterAppsDomain" . }}
  issuerRef:
    name: {{ include "apc-global-overrides.require-certManagerDefaultClusterIssuer" . }}
    kind: ClusterIssuer
    group: cert-manager.io
