apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-instance.labels" . | nindent 4 }}
spec:
  version: {{ .Values.elasticsearch.version }}
  auth:
    fileRealm:
    - secretName: es-default-user
    - secretName: {{ .Release.Name }}-snap-repo-init
    roles:
    - secretName: {{ .Release.Name }}-snap-repo-init-role
  nodeSets:
  - name: default
    count: {{ .Values.elasticsearch.nodesCount }}
    podTemplate:
      metadata: {}
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: {{ .Values.elasticsearch.requests.memory }}
              cpu: {{ .Values.elasticsearch.requests.cpu }}
            limits:
              memory: {{ .Values.elasticsearch.limits.memory }}
              cpu: {{ .Values.elasticsearch.limits.cpu }}
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.elasticsearch.volumeClaim.size }}
        storageClassName: {{ .Values.elasticsearch.volumeClaim.storageClass }}
  http:
    tls:
      certificate:
        secretName: {{ .Release.Name }}-es-tls
