{{- $env := include "apc-global-overrides.environmentShort" $ }}
{{- range $user, $userData := .Values.users }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ $userData.name }}-user
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "eck-instance.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ $.Values.secretStore }}
  refreshInterval: "1h0m0s"
  target:
    name: {{ $.Release.Name }}-{{ $userData.name }}-user
    deletionPolicy: Retain
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ printf "%s/%s/elasticsearch/%s" $env $.Release.Namespace $userData.name }}
---
{{- end }}
