{{- if .Values.elasticsearch.route }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-es
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-instance.labels" . | nindent 4 }}
spec:
  #host: elasticsearch.example.com
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  to:
    kind: Service
    name: {{ .Release.Name }}-es-http
{{- end }}
