{{- range $user, $userData := .Values.users }}
{{- if $userData.customRoles }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ $.Release.Name }}-{{ $userData.name }}-role
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "eck-instance.labels" $ | nindent 4 }}
stringData:
  roles.yml: |-
    {{- $userData.customRoles | nindent 4 }}
---
{{- end }}
{{- end }}
