kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-slm-admin-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-instance.labels" $ | nindent 4 }}
stringData:
  roles.yml: |-
    slm_admin_role:
      cluster:
        - "manage_slm"
        - "cluster:admin/snapshot/*"
      indices:
        - names: [".slm-history-*"]
          privileges: ["read"]
