kind: Secret
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-snap-repo-init-role
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-instance.labels" $ | nindent 4 }}
stringData:
  roles.yml: |-
    snapshot_repo_role:
      cluster:
        - "cluster:admin/repository/*"
