apiVersion: v2
name: hw-monitoring
description: A Helm chart for Loki AlertingRule alerts on HW/infrastructure events (UPS/PDU/XCA)
type: application
version: 1.0.0
dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
