apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-kafka-bridge.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    events {}

    http {
      server {
        listen 8080;

        location / {
          auth_basic "Kafka Bridge";
          auth_basic_user_file /etc/nginx/auth/htpasswd;

          proxy_pass http://{{ .Release.Name }}-bridge-service.ck-kafka.svc.cluster.local:8080;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
      }
    }
