{{- if .Values.kafkaBridge.oauthProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-oauth-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-kafka-bridge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.kafkaBridge.oauthProxy.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-oauth-proxy
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-oauth-proxy
    spec:
      serviceAccountName: {{ .Release.Name }}-oauth-proxy
      containers:
      - name: oauth-proxy
        image: {{ .Values.kafkaBridge.oauthProxy.image.repository }}:{{ .Values.kafkaBridge.oauthProxy.image.tag }}
        imagePullPolicy: {{ .Values.kafkaBridge.oauthProxy.image.pullPolicy }}
        env:
        - name: COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-oauth-proxy-cookie-secret
              key: secret
        args:
        - --skip-auth-regex=^/ready$
        - --skip-auth-regex=^/oauth/healthz$
        - --http-address=:{{ .Values.kafkaBridge.oauthProxy.httpPort }}
        - --https-address=
        - --provider=openshift
        - --openshift-service-account={{ .Release.Name }}-oauth-proxy
        - --upstream=http://{{ .Release.Name }}-bridge-service.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafkaBridge.httpPort }}
        - --cookie-secret=${COOKIE_SECRET}
        - --openshift-sar={"namespace":"{{ .Release.Namespace }}","resource":"secrets","resourceName":"{{ .Release.Name }}-account-access","verb":"edit"}
        - --openshift-delegate-urls={"/":{"group":"","resource":"secrets","verb":"edit","namespace":"{{ .Release.Namespace }}","name":"{{ .Release.Name }}-account-access"}}
        ports:
        - containerPort: {{ .Values.kafkaBridge.oauthProxy.httpPort }}
          name: http
        resources:
          requests:
            memory: "{{ .Values.kafkaBridge.oauthProxy.resources.requests.memory }}"
            cpu: "{{ .Values.kafkaBridge.oauthProxy.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.kafkaBridge.oauthProxy.resources.limits.memory }}"
            cpu: "{{ .Values.kafkaBridge.oauthProxy.resources.limits.cpu }}"
        livenessProbe:
          httpGet:
            path: /oauth/healthz
            port: {{ .Values.kafkaBridge.oauthProxy.httpPort }}
          initialDelaySeconds: {{ .Values.kafkaBridge.oauthProxy.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.kafkaBridge.oauthProxy.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.kafkaBridge.oauthProxy.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.kafkaBridge.oauthProxy.livenessProbe.failureThreshold }}
        readinessProbe:
          httpGet:
            path: /ready
            port: {{ .Values.kafkaBridge.oauthProxy.httpPort }}
          initialDelaySeconds: {{ .Values.kafkaBridge.oauthProxy.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.kafkaBridge.oauthProxy.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.kafkaBridge.oauthProxy.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.kafkaBridge.oauthProxy.readinessProbe.failureThreshold }}
{{- end }}
