apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-kafka-bridge.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 8080

        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL        

        volumeMounts:
        - name: config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf

        - name: auth
          mountPath: /etc/nginx/auth
        
        - name: cache
          mountPath: /var/cache/nginx

        - name: run
          mountPath: /var/run

      volumes:
      - name: config
        configMap:
          name: {{ .Release.Name }}-nginx

      - name: auth
        secret:
          secretName: {{ .Release.Name }}-user
          items:
          - key: auth
            path: htpasswd

      - name: cache
        emptyDir: {}

      - name: run
        emptyDir: {}
