{{- range $ns, $nsData := .Values.bridgeNS }}
{{- if and $nsData.networkPolicy $nsData.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $.Release.Name }}-{{ $ns }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "apps-kafka-bridge.labels" $ | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: {{ $ns }}
    ports:
    - protocol: TCP
      port: {{ $.Values.kafkaBridge.oauthProxy.httpPort }}
---
{{- end }}
{{- end }}
