{{- if .Values.kafkaBridge.oauthProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oauth-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-kafka-bridge.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: {{ .Values.kafkaBridge.oauthProxy.httpPort }}
  selector:
    app: {{ .Release.Name }}-oauth-proxy
  type: ClusterIP
{{- end }}
