apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-kafka-bridge.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-nginx
  type: ClusterIP
