{{- range $ns, $nsData := .Values.bridgeApps }}
{{- if and $.Values.kafkaBridge.oauthProxy.enabled (not $nsData.appSa) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Release.Name }}-account-access
  namespace: {{ $ns }}
  labels:
    {{- include "apps-kafka-bridge.labels" $ | nindent 4 }}
---
{{- end }}
{{- end }}
