{{- if .Values.kafkaBridge.oauthProxy.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-oauth-proxy
  namespace: {{ .Release.Namespace }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Release.Name }}"}}'
  labels:
    {{- include "apps-kafka-bridge.labels" . | nindent 4 }}
{{- end }}
