apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-kafka-bridge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: {{ .Release.Name }}
      strimzi.io/name: {{ .Release.Name }}-bridge
  endpoints:
  - port: rest-api
    path: /metrics
    interval: 30s
