{{- if .Values.reminders }}
{{- $defaultLabels := .Values.defaultLabels | default dict }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "monitoring-reminder.labels" . | nindent 4 }}
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: monitoring-reminder.rules
    rules:
    {{- range .Values.reminders }}
    {{- $dt := .datetime }}
    {{- if not (contains " " $dt) }}{{- $dt = printf "%s 00:00" $dt }}{{- end }}
    {{- $unixTs := toDate "02.01.2006 15:04 -07:00" (printf "%s +00:00" $dt) | unixEpoch }}
    {{- $days := default 30 .daysBeforeExpiry }}
    {{- $mergedLabels := merge (deepCopy (default dict .labels)) $defaultLabels }}
    - alert: {{ .alert }}
      annotations:
        summary: {{ .summary | quote }}
        description: {{ .description | quote }}
        {{- if .runbookUrl }}
        runbook_url: {{ .runbookUrl | quote }}
        {{- end }}
      expr: |
        ({{ $unixTs }} - time()) / 86400 < {{ $days }}
      labels:
        severity: warning
        {{- with $mergedLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- if .critical }}
    - alert: {{ .alert }}Critical
      annotations:
        summary: {{ .summary | quote }}
        description: {{ .description | quote }}
        {{- if .runbookUrl }}
        runbook_url: {{ .runbookUrl | quote }}
        {{- end }}
      expr: |
        ({{ $unixTs }} - time()) / 86400 < 1
      labels:
        severity: critical
        {{- with $mergedLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
