apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: isas
spec:
  deletionPolicy: Delete
  forProvider:
    realmId: AppDEV
    clientId: isas # must match name of the microserviceaccess!
    name: isas # human readable format
    description: isas description
    accessType: CONFIDENTIAL
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    baseUrl: https://isas.example.com
    rootUrl: https://isas.example.com
    useRefreshTokens: true
    validRedirectUris:
    - https://isas.example.com/login
    webOrigins:
    - https://isas.example.com
    frontchannelLogoutEnabled: true
    pkceCodeChallengeMethod: S256
    fullScopeAllowed: false
  providerConfigRef:
    name: keycloak-provider-config
