apiVersion: ck.socpoist.sk/v1alpha1
kind: Microservice
metadata:
  name: bpm-test-prime
  namespace: bpm-test-prime
spec:
  roles:
    - admin
    - worker
    - reader

  rootUrl: https://bpm-test-prime.apps.example.com/admin/processes
  baseUrl: https://bpm-test-prime.apps.example.com
  validRedirectUris:
    - https://bpm-test-prime.apps.example.com/admin/q/oidc/callback
  webOrigins:
    - https://bpm-test-prime.apps.example.com/admin/processes
