# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

bamoe:
  clientId: bamoe-management-console
  clientName: bamoe

  rootUrl: ~
  baseUrl: ~
  validRedirectUris: []
  webOrigins: []

## uses following global values => do not set here
# global:
#   apc:
#     services:
#       crossplane:
#         kubeKeycloakProviderConfigName: ~
#       keycloak:
#         realm: ~
## and their local overrides
# environmentShort: ~
# services:
#   crossplane:
#     kubeKeycloakProviderConfigName: ~
#       keycloak:
#         realm: ~
