apiVersion: v2
name: msqsql-server
description: A Helm chart for SQL Server
type: application
version: 0.0.1
appVersion: 2019.cu15
icon: https://docs.microsoft.com/vi-vn/troubleshoot/media/hub-landing/sql-database-blue.svg
