global:
  apc:
    environmentShort: p
    proxy: http://proxy.example.com:8080
    noProxy: .example.com,.svc,.cluster.local,localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12
    ntpServers:
      - 10.0.0.11
      - 10.0.0.12
    caCertificates:
      root-ca.crt: |
        -----BEGIN CERTIFICATE-----
        MIIBxTCCAW+gAwIBAgIJAExample
        -----END CERTIFICATE-----
    sshAuthorizedKeys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN45Yki8PhtTZ7NFk9xST9LHvrPgmHuSTHXI2CdXLxzF ops@example.com"
    cluster:
      rootDomain: cloud.example.com
    imageProxy:
      host: my-registry.example.com
      sources:
        - quay.io
        - registry.connect.redhat.com
        - registry.redhat.io
        - docker.io
        - ghcr.io
    adIntegration:
      name: AD Login
      ldap:
        attributes:
          url: "ldaps://ad.example.com/DC=example,DC=com?sAMAccountName?sub?(objectClass=person)"
          bindDN: "CN=svc-ocp,OU=Service Accounts,DC=example,DC=com"
    ldapIntegration:
      name: LDAP Login
      ldap:
        attributes:
          url: "ldaps://ldap.example.com/OU=Users,dc=example,dc=com?uid"
          bindDN: "cn=svc-ocp,ou=Technical-Accounts,ou=prod,ou=Users,dc=example,dc=com"
    services:
      externalSecretsOperator:
        defaultClusterSecretStore: vault
      vault:
        KVmountPlatform: apc-platform
      certManager:
        defaultClusterIssuer: vault-issuer

clusterName: example01
releaseImage: "quay.io/openshift-release-dev/ocp-release:4.17.11-multi"

nodePool:
  replicas: 4
  nodeLabels:
    k8s.ovn.org/egress-assignable: ""

services:
  oauthPort: 30102
  konnectivityPort: 30103
  ignitionPort: 30104
  oidcPort: 30101
