acm-operatorpolicy:
  subscription:
    channel: stable
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: kubernetes-nmstate-operator.4.17.0-202502250404
  upgradeApproval: Automatic
  versions:
    - kubernetes-nmstate-operator.4.17.0-202502250404
