apiVersion: v2
name: monitoring-reminder
description: A Helm chart for setting up PrometheusRule alerts for static date-based reminders (e.g. secret/certificate expiry)
type: application
version: 2.0.1
