# releaseServiceOverride: ArgoCD

reminders:
  OIDCVaultSecretExpirySoon:
    summary: Azure Entra ID secret for vault.lab.gr8it.cloud OIDC expires in less than 30 days
    description: >
      Azure Entra ID client secret used for OIDC authentication in vault.lab.gr8it.cloud expires
      in less than 30 days. The secret is stored in Azure App Registration. After expiry, login
      to Vault via OIDC will stop working.
    datetime: "01.04.2027" # UTC!
    runbookUrl: "https://github.com/company/repo/runbook.md" # optional
    critical: true # optional
