apiVersion: v2
name: odf-config
description: A Helm chart to configure OpenShift Data Foundation (ODF) additional networks
type: application
version: 1.0.1
dependencies:
  - name: apc-global-overrides
    version: "1.8.0"
    repository: "https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/"
