additionalNetworks: []

storageCluster:
  name: ocs-storagecluster
  nodeCount: 0
  localVolumeSetCount: 0
  deviceMinSize: 6000Gi
  resourceProfile: balanced
  resources: {}
  cephCluster: {}

machineConfig:
  enabled: false
  configMap:
    name: machineconfig-99-bond1-promisc
