apiVersion: v2
name: multi-cluster-observability
description: A Helm chart for ACM MultiClusterObservability and related observability resources
type: application
version: 1.0.0
appVersion: "v1beta2"
