apiVersion: v2
name: multi-cluster-observability
description: A Helm chart for ACM MultiClusterObservability and related observability resources
type: application
version: 1.0.0

dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
