global:
  apc:
    cluster:
      isHub: true
    services:
      externalSecretsOperator:
        defaultClusterSecretStore: vault-hub-secret-store

alertmanagerConfig:
  vault:
    key: customers/socpoist/msteams
    property: sp-apc-alerts-!hub-url
