metricsAllowlists:
  enabled: true
  configMaps:
    - name: observability-metrics-custom-allowlist
      namespace: open-cluster-management-observability
      dataKey: metrics_list.yaml
      names:
        - kube_namespace_labels
        - ocs_rgw_health_status
        - odf_system_health_status
        - ceph_health_status
        - kube_pod_labels
        - kube_secret_owner
        - kube_persistentvolumeclaim_info
    - name: observability-metrics-custom-allowlist
      namespace: apc-blackbox-exporter
      dataKey: uwl_metrics_list.yaml
      names:
        - probe_success
    - name: observability-metrics-custom-allowlist
      namespace: apc-vault
      dataKey: uwl_metrics_list.yaml
      names:
        - vault_core_active
