apiVersion: v2
name: cluster-infraenv
description: Deploys an InfraEnv and related resources for a Hosted Control Plane cluster on an ACM hub
type: application
version: 1.0.0
dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
