global:
  apc:
    environmentShort: p
    proxy: http://proxy.example.com:8080
    noProxy: .example.com,.svc,.cluster.local,localhost
    ntpServers:
      - 10.0.0.1
      - 10.0.0.2
    sshAuthorizedKeys: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIN45Yki8PhtTZ7NFk9xST9LHvrPgmHuSTHXI2CdXLxzF ops@example.com"
    services:
      externalSecretsOperator:
        defaultClusterSecretStore: vault
      vault:
        KVmountPlatform: apc-platform

envName: prod01
agentEnvironment: prod

nmStateConfigs:
  - name: node-01
    interfaces:
      - macAddress: "aa:bb:cc:dd:ee:01"
        name: ens7f0np0
      - macAddress: "aa:bb:cc:dd:ee:02"
        name: ens13f0np0
    config:
      interfaces:
        - name: bond0
          type: bond
          state: up
          ipv4:
            address:
              - ip: 10.0.10.10
                prefix-length: 24
            enabled: true
          link-aggregation:
            mode: 802.3ad
            options:
              miimon: '140'
              xmit_hash_policy: layer2
            port:
              - ens7f0np0
              - ens13f0np0
      dns-resolver:
        config:
          server:
            - 10.0.0.11
            - 10.0.0.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.0.10.1
            next-hop-interface: bond0
            table-id: 254
  - name: node-02
    interfaces:
      - macAddress: "aa:bb:cc:dd:ee:03"
        name: ens7f0np0
      - macAddress: "aa:bb:cc:dd:ee:04"
        name: ens13f0np0
    config:
      interfaces:
        - name: bond0
          type: bond
          state: up
          ipv4:
            address:
              - ip: 10.0.10.11
                prefix-length: 24
            enabled: true
          link-aggregation:
            mode: 802.3ad
            options:
              miimon: '140'
              xmit_hash_policy: layer2
            port:
              - ens7f0np0
              - ens13f0np0
      dns-resolver:
        config:
          server:
            - 10.0.0.11
            - 10.0.0.12
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 10.0.10.1
            next-hop-interface: bond0
            table-id: 254
