global:
  apc:
    environmentShort: p
    services:
      externalSecretsOperator:
        defaultClusterSecretStore: vault
      vault:
        KVmountPlatform: apc-platform

envName: prod02

nmStateConfigs:
  - name: node-01
