{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
---
# Allows the OAuth proxy to perform token reviews against the API server.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pushgateway-helm.fullname" . }}-tokenreview
  labels:
    {{- include "pushgateway-helm.labels" . | nindent 4 }}
rules:
  - apiGroups: [authentication.k8s.io]
    resources: [tokenreviews]
    verbs: [create]
  - apiGroups: [authorization.k8s.io]
    resources: [subjectaccessreviews]
    verbs: [create]
{{- end }}
