---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "pushgateway-helm.fullname" . }}-oauth-cookie
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushgateway-helm.labels" . | nindent 4 }}
spec:
  length: 32
  digits: 6
  symbols: 0
  noUpper: false
  allowRepeat: true
