---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "pushgateway-helm.fullname" . }}-oauth-cookie
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushgateway-helm.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  target:
    name: pushgateway-oauth-cookie-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          {{- include "pushgateway-helm.labels" . | nindent 10 }}
      data:
        cookie-secret: "{{ `{{ . }}` }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: {{ include "pushgateway-helm.fullname" . }}-oauth-cookie
