{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pushgateway-helm.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pushgateway-helm.labels" . | nindent 4 }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ include "pushgateway-helm.routeName" . }}"}}
{{- end }}
