{{- if .Values.instanceReport.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ (index .Values "mongodb-kubernetes").operator.name }}-report
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mongodb-operator-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: instance-report
{{- end }}
