# OperatorPolicy Values
acm-operatorpolicy:
  subscription:
    channel: stable-4.17
    name: odf-operator
    namespace: openshift-storage
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: odf-operator.v4.17.5-rhodf

  upgradeApproval: Automatic
  versions:
    - odf-operator.v4.17.5-rhodf
