---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana-instance.name" . }}-sa-token
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kubernetes.io/service-account.name: {{ include "grafana-instance.name" . }}-sa
  labels:
    {{- include "grafana-instance.labels" . | nindent 4 }}
type: kubernetes.io/service-account-token
