acm-operatorpolicy:
  subscription:
    channel: stable
    name: rhacs-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: rhacs-operator.v4.11.4

  upgradeApproval: Automatic
  versions:
    - rhacs-operator.v4.8.7
    - rhacs-operator.v4.9.3
    - rhacs-operator.v4.10.9
    - rhacs-operator.v4.11.4
