apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: test
spec:
  destination:
    namespace: test
    server: https://kubernetes.default.svc
  project: test
  source:
    helm:
      releaseName: test
      valueFiles:
        - ../../values.dev.yaml
    path: charts/apc-moodle
    repoURL: https://gitlab.socpoist.sk/moodle/moodle.git
    targetRevision: HEAD
