apiVersion: v2
name: logging-operators
description: A Helm chart to install logging operators (Cluster Observability Operator, Loki Operator, OpenShift Logging Operator)
type: application
version: 1.0.0
dependencies:
  - name: apc-global-overrides
    version: 1.6.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
