operators:
  coo:
    enabled: true
    channel: "stable-1.2"
    csv: "cluster-observability-operator.v1.2.2"
    installPlanApproval: Manual
    namespace: openshift-cluster-observability-operator
  loki:
    enabled: true
    channel: "stable-6.1"
    csv: "loki-operator.v6.1.0"
    installPlanApproval: Manual
    namespace: openshift-operators-redhat
  logging:
    enabled: true
    channel: "stable-6.1"
    csv: "cluster-logging.v6.1.0"
    installPlanApproval: Manual
    namespace: openshift-logging

namespaces:
  coo:
    create: true
  operatorsRedhat:
    create: true
  logging:
    create: true
