# --- Cluster Observability Operator ---
coo-operatorpolicy:
  enabled: true
  subscription:
    channel: "stable-1.2"
    name: cluster-observability-operator
    namespace: openshift-cluster-observability-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cluster-observability-operator.v1.2.2
  operatorGroup:
    name: openshift-cluster-observability-operator
    namespace: openshift-cluster-observability-operator
    targetNamespaces:
      - openshift-cluster-observability-operator
  upgradeApproval: None
  versions:
    - cluster-observability-operator.v1.2.2

# --- Loki Operator ---
loki-operatorpolicy:
  enabled: true
  subscription:
    channel: "stable-6.1"
    name: loki-operator
    namespace: openshift-operators-redhat
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: loki-operator.v6.1.0
  operatorGroup:
    name: openshift-operators-redhat
    namespace: openshift-operators-redhat
    targetNamespaces:
      - openshift-operators-redhat
  upgradeApproval: None
  versions:
    - loki-operator.v6.1.0

# --- OpenShift Logging Operator ---
logging-operatorpolicy:
  enabled: true
  subscription:
    channel: "stable-6.1"
    name: cluster-logging
    namespace: openshift-logging
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cluster-logging.v6.1.0
  operatorGroup:
    name: openshift-logging
    namespace: openshift-logging
    targetNamespaces:
      - openshift-logging
  upgradeApproval: None
  versions:
    - cluster-logging.v6.1.0
