{{- range .Values.hostedClusters }}
{{- $name := required "hostedClusters[].name is required" .name }}
apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ printf "hcp-%s" $name | quote }}
  namespace: {{ $.Values.namespace | default $.Release.Namespace | quote }}
  labels:
    {{- include "openshift-adp-backups.labels" $ | nindent 4 }}
spec:
  schedule: {{ required "hostedClusters[].schedule is required" .schedule | quote }}
  paused: {{ .paused | default false }}
  template:
    includedNamespaces:
      - {{ $name }}
      - {{ printf "%s-%s" $name $name }}
      - {{ printf "klusterlet-%s" $name }}
    includedNamespaceScopedResources:
      - '*'
    excludedNamespaceScopedResources:
      - events
      - events.events.k8s.io
      - pods
      - replicasets.apps
    includedClusterScopedResources:
      - managedclusters.cluster.open-cluster-management.io
    snapshotMoveData: false
    defaultVolumesToFSBackup: false
    ttl: {{ .ttl | default "336h0m0s" | quote }}
---
{{- end }}
