{{- range .Values.hostedClusters }}
{{- $name := required "hostedClusters[].name is required" .name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-import" $name | quote }}
  namespace: {{ $name | quote }}
  labels:
    velero.io/exclude-from-backup: "true"
---
{{- end }}
