{
 "title": "99 - Availability Status",
 "tags": [
  "APC",
  "SLO"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Clusters Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OpenShift API",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( \r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (probe_success{target=\"openshift-api\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n   count by (clusterName)(\r\n  count_over_time(\r\n    (probe_success{target=\"openshift-api\"})[5m:30s]\r\n  ))\r\n  * 100\r\n\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenShift Console",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (probe_success{target=\"openshift-console\"}) / count by(clusterName) (probe_success{target=\"openshift-console\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Managed Services Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "IDP service availability - Red Hat build of Keycloak",
   "type": "status-history",
   "description": "IDP service availability - Red Hat build of Keycloak",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by ( clusterName)(\r\n  count_over_time(\r\n    (up{job=\"keycloak-service\", namespace=\"apc-keycloak\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by ( clusterName)(\r\n  count_over_time(\r\n    (up{job=\"keycloak-service\", namespace=\"apc-keycloak\"})[5m:30s]\r\n  ))\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n count by (clusterName)(\r\n count_over_time(\r\n  (up{job=\"openshift-operators/cnpg-controller-manager\"} == 1)[5m:30s]\r\n ))\r\n /\r\n count by (clusterName)(\r\n count_over_time(\r\n  (up{job=\"openshift-operators/cnpg-controller-manager\"})[5m:30s]\r\n ))\r\n * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{job=\"apc-mongodb-operator/mongodb-operator-podmonitor\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{job=\"apc-mongodb-operator/mongodb-operator-podmonitor\"})[5m:30s]\r\n  ))\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{job=\"openshift-operators/strimzi-kafka-operator\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{job=\"openshift-operators/strimzi-kafka-operator\"})[5m:30s]\r\n  ))\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (vault_core_active == 1) [5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (vault_core_active)[5m:30s]\r\n  ))\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab, CICD availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n    count_over_time(\r\n      (up{job=~\"gitlab-.*\"} == 1)[5m:30s]\r\n    )\r\n  )\r\n/\r\n  count by (clusterName)(\r\n    count_over_time(\r\n      up{job=~\"gitlab-.*\"}[5m:30s]\r\n    )\r\n  )\r\n)\r\n* on(clusterName)                     \r\n(\r\n  count by (clusterName)(\r\n    count_over_time(\r\n      (probe_success{target=\"gitlab-webui\"} == 1)[5m:30s]\r\n    )\r\n  )\r\n/\r\n  count by (clusterName)(\r\n    count_over_time(\r\n      probe_success{target=\"gitlab-webui\"}[5m:30s]\r\n    )\r\n  )\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ODF object storage - Ceph RGW availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count(\r\n    count_over_time(\r\n      (ocs_rgw_health_status{job=\"ocs-metrics-exporter\"} != 2)[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  /\r\n  count(\r\n    count_over_time(\r\n      (ocs_rgw_health_status{job=\"ocs-metrics-exporter\"})[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ODF block availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 28 },
   "targets": [
    {
     "expr": "(\r\n  count(\r\n    count_over_time(\r\n      ( ceph_health_status{job=\"rook-ceph-mgr\"} == 0 )[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  /\r\n  count(\r\n    count_over_time(\r\n      ( ceph_health_status{job=\"rook-ceph-mgr\"} )[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ODF file availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count(\r\n    count_over_time(\r\n      ( ceph_health_status{job=\"rook-ceph-mgr\"} == 0 )[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  /\r\n  count(\r\n    count_over_time(\r\n      ( ceph_health_status{job=\"rook-ceph-mgr\"} )[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ODF object storage - Noobaa availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count(\r\n    count_over_time(\r\n      (odf_system_health_status{service=\"noobaa-mgmt\"} == 0)[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  /\r\n  count(\r\n    count_over_time(\r\n      (odf_system_health_status{service=\"noobaa-mgmt\"})[5m:30s]\r\n    )\r\n  ) by (clusterName)\r\n  * 100\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Monitoring",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-monitoring\",job=\"alertmanager-main\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-monitoring\",job=\"alertmanager-main\"})[5m:30s]\r\n  ))\r\n)\r\n*\r\n(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-monitoring\",job=\"prometheus-k8s\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-monitoring\",job=\"prometheus-k8s\"})[5m:30s]\r\n  ))\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Logging",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-logging\", job=\"logging-loki-gateway-http\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-logging\", job=\"logging-loki-gateway-http\"})[5m:30s]\r\n  ))\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Security - ACS",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"stackrox\",job=\"central\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"stackrox\",job=\"central\"})[5m:30s]\r\n  ))\r\n  * 100\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform  Backup-Restore",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-adp\",job=\"openshift-adp-velero-metrics-svc\"} == 1)[5m:30s]\r\n  ))\r\n  /\r\n  count by (clusterName)(\r\n  count_over_time(\r\n    (up{namespace=\"openshift-adp\",job=\"openshift-adp-velero-metrics-svc\"})[5m:30s]\r\n  ))\r\n  * 100\r\n)\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}