{
 "title": "Availability Status",
 "tags": [
  "APC",
  "SLO"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Clusters Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "OpenShift API",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (probe_success{target=\"openshift-api\"}) / count by(clusterName) (probe_success{target=\"openshift-api\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OpenShift Console",
   "type": "status-history",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (probe_success{target=\"openshift-console\"}) / count by(clusterName) (probe_success{target=\"openshift-console\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Managed Services Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ODF block availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "count by(clusterName)  ( ceph_health_status{job=\"rook-ceph-mgr\"} == 0 ) / count by(clusterName)  ( ceph_health_status{job=\"rook-ceph-mgr\"} ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ODF file availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count by(clusterName)  ( ceph_health_status{job=\"rook-ceph-mgr\"} == 0 ) / count by(clusterName)  ( ceph_health_status{job=\"rook-ceph-mgr\"} ) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ODF object storage - noobaa availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count by (clusterName) (odf_system_health_status{service=\"noobaa-mgmt\"} == 0) / count by (clusterName) (odf_system_health_status{service=\"noobaa-mgmt\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ODF object storage - Ceph RGW availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count by (clusterName) (ocs_rgw_health_status{job=\"ocs-metrics-exporter\"} != 2) / count by (clusterName)  (ocs_rgw_health_status{job=\"ocs-metrics-exporter\"}) * 100\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Security - ACS",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by(clusterName) (up{namespace=\"stackrox\",job=\"central\"}) / count by(clusterName) (up{namespace=\"stackrox\",job=\"central\"}) * 100\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Logging",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (up{namespace=\"openshift-logging\", job=\"logging-loki-gateway-http\"}) / count by(clusterName) (up{namespace=\"openshift-logging\", job=\"logging-loki-gateway-http\"}) * 100\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vault availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "count by (clusterName) (vault_core_active == 1) / count by (clusterName) (vault_core_active) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform Monitoring",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(clusterName) (up{namespace=\"openshift-monitoring\",job=\"alertmanager-main\"}) / count by(clusterName) (up{namespace=\"openshift-monitoring\",job=\"alertmanager-main\"})) * (sum by(clusterName) (up{namespace=\"openshift-monitoring\",job=\"prometheus-k8s\"}) / count by(clusterName) (up{namespace=\"openshift-monitoring\",job=\"prometheus-k8s\"})) * 100\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gitlab, CICD availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * avg_over_time(up{job=~\"gitlab-.*\"}[1d])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Platform  Backup-Restore",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (up{namespace=\"openshift-adp\",job=\"openshift-adp-velero-metrics-svc\"}) / count by(clusterName) (up{namespace=\"openshift-adp\",job=\"openshift-adp-velero-metrics-svc\"}) * 100\r\n\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PostgreSQL availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (up{job=\"openshift-operators/cnpg-controller-manager\"}) / count by(clusterName) (up{job=\"openshift-operators/cnpg-controller-manager\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RHBK availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (up{job=\"keycloak-service\", namespace=\"apc-keycloak\"}) / count by(clusterName) (up{job=\"keycloak-service\", namespace=\"apc-keycloak\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (up{job=\"apc-mongodb-operator/mongodb-operator-podmonitor\"}) / count by(clusterName) (up{job=\"apc-mongodb-operator/mongodb-operator-podmonitor\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka availability",
   "type": "status-history",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(clusterName) (up{job=\"openshift-operators/strimzi-kafka-operator\"}) / count by(clusterName) (up{job=\"openshift-operators/strimzi-kafka-operator\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}