apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: app-project-namespace-metadata
  labels:
    {{- include "kyverno-app-project.labels" . | nindent 4 }}
  annotations:
    policies.kyverno.io/title: Patch Namespace labels from the project metadata ConfigMap
    policies.kyverno.io/category: Monitoring
    policies.kyverno.io/subject: project
    policies.kyverno.io/minversion: 1.13.0
spec:
  background: true
  rules:
    - name: set-namespace-labels
      match:
        {{- include "kyverno-app-project.matchMetadataConfigMap" . | nindent 8 }}
      context:
        - name: labelentries
          variable:
            jmesPath: "items(request.object.data, 'key', 'value')[?regex_match('^[a-zA-Z0-9]([-_.a-zA-Z0-9]{0,61}[a-zA-Z0-9])?$', value) && length(key) <= `63`]"
            default: []
      preconditions:
        all:
          - key: {{ `{{ length(labelentries) }}` | quote }}
            operator: GreaterThan
            value: 0
      mutate:
        mutateExistingOnPolicyUpdate: true
        targets:
          - apiVersion: v1
            kind: Namespace
            name: {{ `{{ request.object.metadata.namespace }}` | quote }}
        patchStrategicMerge:
          metadata:
            labels: {{ `{{ object_from_lists(labelentries[].key, labelentries[].value) }}` | quote }}
