{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "logging-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging-helm.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  target:
    name: {{ include "logging-helm.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: TOKEN
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/openshift-logging/hub-spoke-logforward
        property: TOKEN
{{- end }}
