{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging-helm.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  target:
    name: {{ .Values.externalSecret.name }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecret.secretKey }}
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/openshift-logging/hub-spoke-logforward
        property: {{ .Values.externalSecret.secretKey }}
{{- end }}
