{{- if .Values.objectBucketClaim.enabled }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "logging-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging-helm.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.objectBucketClaim.storageClassName }}
  bucketName: {{ .Values.objectBucketClaim.bucketName | default (include "logging-helm.fullname" .) }}
{{- end }}
