{{- if .Values.uiplugin.enabled }}
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
  labels:
    {{- include "logging-helm.labels" . | nindent 4 }}  
spec:
  type: Logging
  logging:
    lokiStack:
      name: {{ .Values.lokistack.name }}
    timeout: 120s
{{- end }}
