# --- Network Observability Operator ---
acm-operatorpolicy:
  subscription:
    channel: "stable"
    name: netobserv-operator
    namespace: openshift-netobserv-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: network-observability-operator.v1.12.3
  upgradeApproval: Automatic
  versions:
    - network-observability-operator.v1.8.0
    - network-observability-operator.v1.8.1
    - network-observability-operator.v1.9.0
    - network-observability-operator.v1.9.1
    - network-observability-operator.v1.9.2
    - network-observability-operator.v1.9.3
    - network-observability-operator.v1.10.0
    - network-observability-operator.v1.10.1
    - network-observability-operator.v1.11.0
    - network-observability-operator.v1.11.1
    - network-observability-operator.v1.11.2
    - network-observability-operator.v1.12.0
    - network-observability-operator.v1.12.1
    - network-observability-operator.v1.12.2
    - network-observability-operator.v1.12.3
