# --- Network Observability Operator ---
acm-operatorpolicy:
  subscription:
    channel: "stable"
    name: netobserv-operator
    namespace: openshift-netobserv-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: network-observability-operator.v1.8.0
  upgradeApproval: Automatic
  versions:
    - network-observability-operator.v1.8.0
