# --- Network Observability Operator ---
netobserv-operatorpolicy:
  enabled: true
  subscription:
    channel: "stable"
    name: netobserv-operator
    namespace: openshift-netobserv-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: netobserv-operator.v1.7.0
  operatorGroup:
    name: openshift-netobserv-operator
    namespace: openshift-netobserv-operator
    targetNamespaces:
      - openshift-netobserv-operator
  upgradeApproval: None
  versions:
    - netobserv-operator.v1.7.0
