global:
  apc:
    environmentShort: d
    services:
      crossplane:
        kubeKeycloakProviderConfigName: keycloak-config
      keycloak:
        realm: apps

bamoe:
  validRedirectUris:
    - https://bamoe.apps.ocp4.example.com/*
