global:
  apc:
    customer: socpoistsk
    environment: dev
    cluster:
      name: dev01
      isHub: true
    proxy: http://proxysp.socpoist.sk:8080
    noProxy: .socpoist.sk,.svc,.cluster.local,localhost,127.0.0.1,127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,172.20.0.1
    proxyCIDRs:
      - 10.1.1.7/32
    vault:
      kvMountPlatform: customers
    services:
      externalSecretsOperator:
        defaultClusterSecretStore: apc

alertmanager:
  eso:
    vault:
      secretPath: customers/socpoist/monitoring/alertmanager

