apiVersion: v2
name: netobserv-helm
description: A Helm chart to configure OpenShift Network Observability (FlowCollector, LokiStack, UIPlugin)
type: application
version: 1.0.0
dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
