apiVersion: v2
name: dynatrace-operator-helm
description: A Helm chart to install Dynatrace Operator
type: application
version: 1.0.0
appVersion: "v1.10.2"
dependencies:
  - name: dynatrace-operator
    version: 1.10.2
    repository: oci://public.ecr.aws/dynatrace
