apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "eck-operator.fullname" . }}-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "eck-operator.labels" . | nindent 4 }}
spec:
  groups: 
  - name: {{ include "eck-operator.fullname" . }}-rules
    rules:
      - alert: ECKOperatorDown
        expr: kube_deployment_status_replicas_available{namespace="{{ .Release.Namespace }}", deployment="elastic-operator"} == 0
          or absent(kube_deployment_status_replicas_available{namespace="{{ .Release.Namespace }}", deployment="elastic-operator"})
        for: 5m
        labels:
          namespace: {{ .Release.Namespace }}
          severity: critical
          team: platform
          vendor: aspecta
        annotations:
          summary: "ECK operator is down"
          description: "ECK operator in namespace {{ `{{ $labels.namespace }}` }} is down for more than 5 minutes."
      - alert: ECKOperatorCrashLooping
        expr: max_over_time(kube_pod_container_status_waiting_reason{namespace="{{ .Release.Namespace }}", pod=~"elastic-operator-.*", reason="CrashLoopBackOff"}[5m]) > 0
        for: 5m
        labels:
          namespace: {{ .Release.Namespace }}
          severity: critical
          team: platform
          vendor: aspecta
        annotations:
          summary: "ECK operator is crashlooping"
          description: "ECK operator in namespace {{ `{{ $labels.namespace }}` }} is crashlooping for more than 5 minutes."
