acm-operatorpolicy:
  subscription:
    channel: stable
    name: elasticsearch-eck-operator-certified
    namespace: eck-operator
    source: certified-operators
    sourceNamespace: openshift-marketplace
    startingCSV: elasticsearch-eck-operator-certified.v3.3.1

  upgradeApproval: Automatic
  versions:
    - elasticsearch-eck-operator-certified.v3.3.1
