acm-operatorpolicy:
  subscription:
    channel: alpha
    name: dynatrace-operator
    namespace: apc-dynatrace
    source: certified-operators
    sourceNamespace: openshift-marketplace
    startingCSV: dynatrace-operator.v1.10.2

  upgradeApproval: Automatic
  versions:
    - dynatrace-operator.v1.10.2
