nameOverride: ""
fullnameOverride: ""

## uses following global values => do not set here
# global:
#   apc:
#     caCertificates: ~ 
#     environmentShort:
#     services:
#       externalSecretsOperator:
#         defaultClusterSecretStore:
#       vault:
#         KVmountPlatform:
## and their local overrides
# caCertificates: ~ # custom CA certificates in PEM format. If not specified, .global.apc.caCertificates is used
# environmentShort:
# services:
#   externalSecretsStore:
#     defaultClusterSecretStore:
#   vault:
#     KVmountPlatform:


# set image proxy for pulling images from external registries
imageProxy:
  # enabled, only if host is specified
  host: ""
  port: 443
  sources: []
  # # should include
  # - registry.redhat.io
  # - registry.connect.redhat.com
  # - docker.io
  # - quay.io
  # - ghcr.io
  caCertificates: ~ # custom CA certificates in PEM format for image proxy. If not specified, .caCertificates / .global.apc.caCertificates is used

# config.openshift.io/v1 OAuth configuration
oauth:
  identityProviders: []

# pull secret to use in cluster
# must exist in <global.apc.vault.KVmountPlatform>/<global.apc.vault.environmentShort>/<vaultKey>
pullSecret:
  enabled: true
  vaultKey: cluster-config
  vaultProperty: pull-secret

dedicatedEtcdStorage: true
dedicatedEtcdStorageConfig: |
  #!/bin/bash
  set -uo pipefail

  devices="/dev/vg1/77c80d55-a815-4f2e-9a5b-bae4d85467a2 \
          /dev/vg1/05316655-58e5-4c70-bc48-46ddb225e6fc \
          /dev/vg1/c82595fb-a1f6-4fbf-a7ec-3eb466873116"

  for device in $devices; do
    /usr/bin/test -b "$device" || continue
    /usr/sbin/blkid "$device" &> /dev/null
    if [ $? == 2  ]; then
      echo "Secondary block device found: $device"
      echo "Creating filesystem for etcd mount"
      /usr/sbin/mkfs.xfs -L var-lib-etcd -f "$device" &> /dev/null
      /usr/sbin/udevadm settle
      /usr/bin/touch /etc/var-lib-etcd-mount
      exit 0
    fi
  done
  echo "Couldn't find secondary block device!" >&2
  exit 77

