apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vector-helm.vectorConfigMapName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-helm.vectorResourceLabels" . | nindent 4 }}
data:
  vector.yaml: |
{{ include "vector-helm.vectorConfig" . | fromYaml | toYaml | indent 4 }}
