apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: siem-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-helm.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: siem-token
    creationPolicy: Merge
  data:
    - secretKey: token
      remoteRef:
        key: {{ include "apc-global-overrides.vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.environmentShort" . }}/vector/siem-token
        property: token
