apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jira-ops
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-helm.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.jiraOpsExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: jira-ops
    creationPolicy: Owner
  data:
    - secretKey: authorization
      remoteRef:
        # Expected value format: authorization = "GenieKey <api-key>"
        key: {{ include "apc-global-overrides.vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.environmentShort" . }}/vector/jira-ops
        property: authorization
