{{- $defaultKey := printf "%s/%s/vector/siem-token" (include "apc-global-overrides.vaultKVmountPlatform" .) (include "apc-global-overrides.environmentShort" .) -}}
{{- $remoteKey := .Values.siemTokenExternalSecret.key | default $defaultKey -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: siem-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-helm.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.siemTokenExternalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: siem-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: {{ $remoteKey }}
        property: {{ .Values.siemTokenExternalSecret.property }}
