{{- if and .Values.vectorMetalLB.enabled (gt (len .Values.vectorMetalLB.addresses) 0) }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vector-reserved
  namespace: {{ include "apc-global-overrides.metallbNamespace" . }}
  labels:
    {{- include "vector-helm.labels" . | nindent 4 }}
spec:
  addresses:
    {{- range .Values.vectorMetalLB.addresses }}
    - {{ . }}
    {{- end }}
  autoAssign: {{ .Values.vectorMetalLB.autoAssign }}
  serviceAllocation:
    namespaces:
      - {{ .Release.Namespace }}
    serviceSelectors:
      - matchLabels:
          {{- include "vector-helm.vectorSelectorLabels" . | nindent 10 }}
{{- end }}
