{{- if gt (len (.Values.vectorMetalLB.addresses | default list)) 0 }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vector-reserved
  namespace: {{ include "apc-global-overrides.metallbNamespace" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  addresses:
    {{- range .Values.vectorMetalLB.addresses }}
    - {{ . }}
    {{- end }}
  autoAssign: {{ .Values.vectorMetalLB.autoAssign }}
  serviceAllocation:
    namespaces:
      - {{ .Release.Namespace }}
    serviceSelectors:
      - matchLabels:
          app.kubernetes.io/name: vector
{{- end }}
