{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "vector-helm.vectorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-helm.vectorResourceLabels" . | nindent 4 }}
spec:
  jobLabel: app.kubernetes.io/name
  selector:
    matchLabels:
      {{- include "vector-helm.vectorSelectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  podMetricsEndpoints:
    - port: prom-exporter
      path: /metrics
      honorLabels: false
      honorTimestamps: true
{{- end }}
