apiVersion: v1
kind: Secret
metadata:
  name: vector-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-helm.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "vector-helm.vectorServiceAccountName" . }}
type: kubernetes.io/service-account-token
