apiVersion: v1
kind: Service
metadata:
  name: {{ include "vector-helm.vectorFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "vector-helm.vectorResourceLabels" . | nindent 4 }}
  {{- if .Values.vectorMetalLB.enabled }}
  annotations:
    metallb.universe.tf/address-pool: vector-reserved
  {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: udp-syslog
      protocol: UDP
      port: 9441
      targetPort: 9441
    - name: tcp-syslog
      protocol: TCP
      port: 9442
      targetPort: 9442
    - name: webhook
      protocol: TCP
      port: 9444
      targetPort: 9444
  selector:
    {{- include "vector-helm.vectorSelectorLabels" . | nindent 4 }}
