mongodb-kubernetes:
  # Set this to true if your cluster is managing SecurityContext for you.
  # If running OpenShift (Cloud, Minishift, etc.), set this to true.
  managedSecurityContext: true
  operator:
    # Namespaces that the Kubernetes Operator watches for MongoDB resource changes. 
    watchNamespace: "*"

    telemetry:
      enabled: false

instanceReport:
  enabled: true
  image:
    repository: registry.k8s.io/kube-state-metrics/kube-state-metrics
    tag: v2.13.0
  ports:
    metrics: 8080
    telemetry: 8081
  scrapeInterval: 30s
  resources:
    requests:
      cpu: 100m
      memory: 300Mi
    limits:
      cpu: 200m
      memory: 512Mi
