{{- if and .Values.alertmanagerUWM.enabled .Values.alertmanagerUWM.eso.enabled }}
{{- $am := .Values.alertmanagerUWM.eso }}
{{- $proxy := include "apc-global-overrides.proxy" . }}
{{- $noProxy := include "apc-global-overrides.noProxy" . }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-user-workload
  namespace: openshift-user-workload-monitoring
  labels:
    {{- include "metrics-helm.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ $am.refreshInterval | quote }}
  target:
    name: alertmanager-user-workload
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/component: alert-router
          app.kubernetes.io/instance: user-workload
          app.kubernetes.io/managed-by: cluster-monitoring-operator
          app.kubernetes.io/name: alertmanager
          app.kubernetes.io/part-of: openshift-monitoring
      data:
        alertmanager.yaml: |
          global:
            http_config:
              proxy_url: {{ $proxy }}
              no_proxy: {{ $noProxy }}
          inhibit_rules:
          - equal:
            - namespace
            - alertname
            source_matchers:
            - "severity = critical"
            target_matchers:
            - "severity =~ warning|info"
          - equal:
            - namespace
            - alertname
            source_matchers:
            - "severity = warning"
            target_matchers:
            - "severity = info"
          receivers:
          - name: "null"
          - name: teams_aspecta
            msteams_configs:
              - send_resolved: true
                webhook_url: {{ `{{ .msteams_url }}` }}
          - name: healthchecksioUWMthanos
            webhook_configs:
              - url: {{ `{{ .healthchecks_url }}` }}
                send_resolved: false
          - name: atlassian_aspecta
            opsgenie_configs:
              - send_resolved: true
                api_key: {{ `{{ .opsgenie_key }}` }}
                message: |
                  [{{ `{{ "{{" }} .CommonLabels.customerName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.clusterName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.severity {{ "}}" }}` }}] -
                  {{ `{{ "{{" }} range .Alerts {{ "}}" }}` }}
                  {{ `{{ "{{" }} if .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} else if .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} else {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.message {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
                  {{ `{{ "{{" }} end {{ "}}" }}` }}
                priority: '{{ `{{ "{{" }} if eq .CommonLabels.severity "critical" {{ "}}" }}` }}P1{{ `{{ "{{" }} else if eq .CommonLabels.severity "warning" {{ "}}" }}` }}P2{{ `{{ "{{" }} else if eq .CommonLabels.severity "info" {{ "}}" }}` }}P3{{ `{{ "{{" }} else {{ "}}" }}` }}P4{{ `{{ "{{" }} end {{ "}}" }}` }}'
                tags: |
                  {{ `{{ "{{" }} with .CommonLabels.clusterName {{ "}}" }}` }}clusterName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.customerName {{ "}}" }}` }}customerName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.environment {{ "}}" }}` }}environment={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.location {{ "}}" }}` }}location={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.namespace {{ "}}" }}` }}namespace={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.severity {{ "}}" }}` }}severity={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.team {{ "}}" }}` }}team={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.vendor {{ "}}" }}` }}vendor={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
                  {{ `{{ "{{" }} with .CommonLabels.app {{ "}}" }}` }}app={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
          route:
            group_by:
            - namespace
            - alertname
            - severity
            group_interval: 5m
            group_wait: 30s
            receiver: teams_aspecta
            repeat_interval: 12h
            routes:
            - receiver: atlassian_aspecta
              continue: true
              matchers:
              - severity =~ "warning|critical"
              - alertname != Watchdog
              - vendor = "aspecta"
              - team = "platform"
            - receiver: healthchecksioUWMthanos
              matchers:
              - alertname = WatchdogUWMthanos
              group_wait: 0s
              group_interval: 60s
              repeat_interval: 60s
            - receiver: "null"
              matchers:
              - severity =~ "info|none"
            - receiver: "null"
              matchers:
              - vendor != "aspecta"
  data:
  - secretKey: msteams_url
    remoteRef:
      key: {{ required "alertmanagerUWM.eso.vault.msteamsKey is required" $am.vault.msteamsKey }}
      property: {{ required "alertmanagerUWM.eso.vault.msteamsProperty is required" $am.vault.msteamsProperty }}
  - secretKey: healthchecks_url
    remoteRef:
      key: {{ required "alertmanagerUWM.eso.vault.healthchecksKey is required" $am.vault.healthchecksKey }}
      property: {{ required "alertmanagerUWM.eso.vault.healthchecksProperty is required" $am.vault.healthchecksProperty }}
  - secretKey: opsgenie_key
    remoteRef:
      key: {{ required "alertmanagerUWM.eso.vault.opsgenieKey is required" $am.vault.opsgenieKey }}
      property: {{ required "alertmanagerUWM.eso.vault.opsgenieProperty is required" $am.vault.opsgenieProperty }}
{{- end }}
