## uses following global values => do not set here
# global:
#   apc:
#     cluster:
#       appsDomain:
## and their local overrides
# cluster.appsDomain:

releaseServiceOverride: ArgoCD

bridgeNS: {}

# list of namespaces which want to use the kafka bridge
# bridgeNS:
#   <namespace>:
##    create networkpolicy to allow connection from the namespace if application is communicating to the bridge service
#     networkPolicy:
#       enabled: false
##    serivce account of application, will be used authentication to the bridge service if oauth proxy is enabled
#     appSa: ~


kafkaBridge:
  bootstrapServers: 
    - "ck-kafka-kafka-bootstrap.ck-kafka.svc:9093"
  replicas: 2
  user: ~
  httpPort: 8080
  producer:
    deliveryTimeout: 300000
  jvmOpts:
    "Xmx": "1g"
    "Xms": "1g"

  oauthProxy:
    replicas: 2
    httpPort: 8080
    enabled: true
    image:
      repository: registry.redhat.io/openshift4/ose-oauth-proxy
      tag: v4.13
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 256Mi
    livenessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 1
      failureThreshold: 3
    readinessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 3 
      failureThreshold: 3
