{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "netobserv-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netobserv-helm.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  target:
    name: {{ include "netobserv-helm.fullname" . }}-allinfo
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: endpoint
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ .Release.Namespace }}/netobserv-s3
        property: endpoint
    - secretKey: bucketnames
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ .Release.Namespace }}/netobserv-s3
        property: bucketnames
    - secretKey: region
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ .Release.Namespace }}/netobserv-s3
        property: region
    - secretKey: access_key_id
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ .Release.Namespace }}/netobserv-s3
        property: access_key_id
    - secretKey: access_key_secret
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ .Release.Namespace }}/netobserv-s3
        property: access_key_secret
{{- end }}
