{{- if .Values.objectBucketClaim.enabled }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "netobserv-helm.fullname" . }}-rgw
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "netobserv-helm.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.objectBucketClaim.storageClassName }}
  bucketName: {{ .Values.objectBucketClaim.bucketName | default (printf "apc-%s-rgw" (include "netobserv-helm.fullname" .)) }}
{{- end }}
