---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quay-config.name" . }}-postinstall-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
data:
  NAMESPACE: {{ .Release.Namespace }}
  QUAYSERVICE: {{ printf "http://%s-quay-app.%s.svc.cluster.local" (include "quay-config.name" .) .Release.Namespace }}
  QUAYNAME: {{ include "quay-config.name" . }}
  QUAYADMINUSER: {{ .Values.quayConfig.localAdminUser }}
  QUAYADMINSECRET: {{ printf "%s-%s" (include "quay-config.name" .) .Values.quayConfig.localAdminUser }}
  BOOTSTRAPTOKENSECRET: {{ include "quay-config.name" . }}-bootstrap-token
  MANAGEDORGCM: {{ include "quay-config.name" . }}-managed-orgs
