---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quay-config.objname.postinst-env" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
data:
  NAMESPACE: {{ .Release.Namespace }}
  QUAYSERVICE: {{ printf "http://%s-quay-app.%s.svc.cluster.local" (include "quay-config.name" .) .Release.Namespace }}
  QUAYROUTE: {{ printf "%s-quay-%s.%s" (include "quay-config.name" .) .Release.Namespace (include "apc-global-overrides.require-clusterAppsDomain" .) }}
  QUAYNAME: {{ include "quay-config.name" . }}
  QUAYADMINUSER: {{ .Values.quayConfig.localAdminUser }}
  QUAYADMINSECRET: {{ include "quay-config.objname.quayadmin" . }}
  BOOTSTRAPTOKENSECRET: {{ include "quay-config.objname.bootstraptoken" . }}
  ROBOTACCOUNTSECRET: {{ include "quay-config.objname.robotaccounts" . }}
  MANAGEDORGCM: {{ include "quay-config.objname.managedorgs" . }}
  VAULTADDRESS: {{ include "apc-global-overrides.require-vaultUrl" . }}
  UPDATEVAULTSECRETS: {{ (ternary "yes" "no" .Values.vault.updateClusterPullSecrets) | quote }}
  LABELS: |2
    {{ include "quay-config.labels" . | nindent 8 }}
