---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quay-config.name" . }}-debug
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      {{- include "quay-config.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quay-config.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "quay-config.objname.sa" . }}
      initContainers:
        - name: vault-cli
          image: docker.io/hashicorp/vault:1.14.8
          command: ['cp', '/bin/vault', '/vault']
          volumeMounts:
            - name: vault-cli
              mountPath: /vault
      containers:
        - name: debug
          image: {{ .Values.ocImage }}
          command: ['/bin/sh', '-c', 'sleep 1d']
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: {{ include "quay-config.objname.postinst-env" . }}
          env:
            - name: PUSHSECRETLABELS
              value: |2
                {{ include "quay-config.labels" . | nindent 20 }}
            - name: CMLABELS
              value: |2
                {{ include "quay-config.labels" . | nindent 20 }}
            - name: INITORGJOB
              value: {{ include "quay-config.objname.initorg-job" . }}
            - name: REGISTRYCREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ include "quay-config.name" . }}-registry-credentials
                  key: pull-secret
          resources:
            {{- .Values.resourcesOverride.postinstall | toYaml | nindent 12 }}
          volumeMounts:
            - name: postinstall-scripts
              mountPath: /scripts
            - name: vault-cli
              mountPath: /vault
            - name: bootstrap-token
              mountPath: /var/opt/token
      volumes:
        - name: postinstall-scripts
          configMap:
            name: {{ include "quay-config.objname.postinst-scripts" . }}
            defaultMode: 0755
        - name: vault-cli
          emptyDir: {}
        - name: bootstrap-token
          secret:
            secretName: {{ include "quay-config.objname.bootstraptoken" . }}
            items:
              - key: token.json
                path: bootstrap
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
