{{- if .Values.imageProxy.pullSecretVaultPath }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "quay-config.name" . }}-registry-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
  target:
    name: {{ include "quay-config.name" . }}-registry-credentials
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: {{ .Values.imageProxy.pullSecretVaultPath }}
{{- end }}
