---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "quay-config.name" . }}-init-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    argocd.argoproj.io/sync-wave: "20"
spec:
  ttlSecondsAfterFinished: 600
  backoffLimit: 1
  template:
    metadata:
      labels:
        {{- include "quay-config.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "quay-config.name" . }}-postinstall
      containers:
        - name: postinstall
          image: {{ .Values.ocImage }}
          imagePullPolicy: Always
          command: ["/bin/bash", "/scripts/init-admin.sh"]
          env:
            - name: ADMINUSER
              value: {{ .Values.quayConfig.localAdminUser }}
            - name: NAMESPACE
              value: {{ .Release.Namespace }}
            - name: SECRETNAME
              value: {{ printf "%s-%s" (include "quay-config.name" .) .Values.quayConfig.localAdminUser }}
            - name: PUSHSECRETLABELS
              value: |2
                {{ include "quay-config.labels" . | nindent 20 }}
            - name: QUAYSERVICE
              value: {{ printf "http://%s-quay-app.%s.svc.cluster.local" (include "quay-config.name" .) .Release.Namespace }}
          resources:
            {{- .Values.resourcesOverride.postinstall | toYaml | nindent 12 }}
          volumeMounts:
            - name: postinstall-scripts
              mountPath: /scripts
      volumes:
        - name: postinstall-scripts
          configMap:
            name: {{ include "quay-config.name" . }}-postinstall-scripts
            defaultMode: 0755
      restartPolicy: Never
      securityContext: {}
      terminationGracePeriodSeconds: 30
