---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-%s" (include "quay-config.name" .) .Values.quayConfig.localAdminUser }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "21"
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
  selector:
    secret:
      name: {{ printf "%s-%s" (include "quay-config.name" .) .Values.quayConfig.localAdminUser }}
  template:
    metadata:
      labels:
        {{- include "quay-config.labels" . | nindent 8 }}
  data:
    - match:
        remoteRef:
          remoteKey: {{ printf "%s/%s/%s" (include "apc-global-overrides.environmentShort" .) .Release.Namespace .Values.quayConfig.localAdminUser }}
