---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ printf "%s-robot-accounts" (include "quay-config.name" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "31"
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
  selector:
    secret:
      name: {{ printf "%s-robot-accounts" (include "quay-config.name" .) }}
  data:
    - match:
        remoteRef:
          remoteKey: {{ printf "%s/%s/robot-accounts" (include "apc-global-overrides.environmentShort" .) .Release.Namespace }}
