---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: {{ include "quay-config.objname.quayadmin" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  updatePolicy: Replace
  deletionPolicy: None
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
  selector:
    secret:
      name: {{ include "quay-config.objname.quayadmin" . }}
  data:
    - match:
        remoteRef:
          remoteKey: {{ printf "%s/%s/%s" (include "apc-global-overrides.environmentShort" .) .Release.Namespace .Values.quayConfig.localAdminUser }}
