---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "quay-config.name" . }}-postinstall
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
rules:
  - apiGroups: [""]
    resources: ["secrets","configmaps"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames:
      - "{{ printf "%s-%s" (include "quay-config.name" .) .Values.quayConfig.localAdminUser }}"
    verbs: ["get","patch","update","delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames:
      - "{{ printf "%s-managed-orgs" (include "quay-config.name" .) }}"
    verbs: ["get","patch","update","delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ include "quay-config.name" . }}-bootstrap-token"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch"]
    resourceNames: ["{{ include "quay-config.name" . }}-init-organizations"]
  - apiGroups: ["quay.redhat.com"]
    resources: ["quayregistries"]
    verbs: ["get"]
    resourceNames: ["{{ include "quay-config.name" . }}"]
