---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "quay-config.name" . }}-postinstall
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
rules:
  - verbs: [create]
    apiGroups: ['']
    resources: [secrets]
  - verbs: [get,patch,update]
    apiGroups: ['']
    resources: [secrets]
    resourceNames: ["{{ printf "%s-%s" (include "quay-config.name" .) .Values.quayConfig.localAdminUser }}"]
  - verbs: [get]
    apiGroups: ['']
    resources: [secrets]
    resourceNames: ["{{ include "quay-config.name" . }}-bootstrap-token"]
