---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "quay-config.name" . }}-postinstall
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
