---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quay-config.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "quay-config.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "10"
type: Opaque
stringData:
  config.yaml: |
    {{- tpl ($.Files.Get "files/config.yaml.tpl") $ | nindent 4 }}
