apiVersion: v1
kind: Secret
metadata:
  name: brokers-ca-certificate
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "apps-ck-kafka-mm2.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- include "apc-global-overrides.caCertificates" . | nindent 2 }}
