{{- if .Values.limitRange }}
{{- range $namespace, $limits := .Values.limitRange }}
{{- range $limitRangeName, $limitRangeData := $limits }}
apiVersion: v1
kind: LimitRange
metadata:
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
  labels:
    {{- include "application-namespace-config.labels" $ | nindent 4 }}
  name: {{ $limitRangeName }}
  namespace: {{ $namespace }}
spec:
  limits:
  - default:
{{ $limitRangeData.defaultLimits | toYaml | indent 6 }}
    defaultRequest:  
{{ $limitRangeData.defaultRequests | toYaml | indent 6 }}
    type: Container
{{- end }}
{{- end }}
{{- end }}
