nncp:
  enabled: true
  bond:
    mode: 802.3ad
    miimon: "140"
    xmitHashPolicy: layer2
    ports:
      - ens13f1np1
      - ens7f1np1
  vlans:
    - name: bond1.4076
      id: 4076
    - name: bond1.4078
      id: 4078
    - name: bond1.4079
      id: 4079
    - name: bond1.1026
      id: 1026
    - name: bond1.8
      id: 8
  bridges:
    - name: br-1026
      vlan: bond1.1026
    - name: br-4076
      vlan: bond1.4076
    - name: br-8
      vlan: bond1.8

cni:
  namespace: openshift-cnv
  vmlm:
    name: vmlm
    masterInterface: bond1.4079
    ipamRange: "10.14.79.0/25"
    ipamRangeStart: "10.14.79.10"
    ipamRangeEnd: "10.14.79.126"
  bridges:
    - name: vm-br-1026
      bridge: br-1026
    - name: vm-br-4076
      bridge: br-4076
    - name: vm-br-8
      bridge: br-8

hyperConverged:
  namespace: openshift-cnv
  virtualMachineOptions:
    disableFreePageReporting: false
    disableSerialConsoleLog: true
  higherWorkloadDensity:
    memoryOvercommitPercentage: 100
  liveMigrationConfig:
    allowAutoConverge: false
    allowPostCopy: false
    completionTimeoutPerGiB: 800
    network: vmlm
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
  evictionStrategy: LiveMigrateIfPossible
  vmStateStorageClass: ocs-storagecluster-cephfs
