acm-operatorpolicy:
  subscription:
    channel: "stable-6.1"
    name: loki-operator
    namespace: openshift-operators-redhat
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: loki-operator.v6.1.3
  operatorGroup:
    name: openshift-operators-redhat
    namespace: openshift-operators-redhat
  upgradeApproval: Automatic
  versions:
    - loki-operator.v6.1.3
