{{- if .Values.eso.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alertmanager-receivers
  namespace: openshift-monitoring
  labels:
    {{- include "monitoring.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.eso.refreshInterval | quote }}
  target:
    name: alertmanager-receivers
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ required "alertmanager.vault.secretPath is required" .Values.alertmanager.vault.secretPath }}
{{- end }}
