{{- if .Values.alertmanager.eso.enabled }}
{{- $hub := .Values.hub }}
{{- $proxy := include "apc-global-overrides.proxy" . }}
{{- $noProxy := include "apc-global-overrides.noProxy" . }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
  labels:
    {{- include "cluster-monitoring.labels" . | nindent 4 }}
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      http_config:
        proxy_url: {{ $proxy }}
        no_proxy: {{ $noProxy }}
    inhibit_rules:
    - equal:
      - namespace
      - alertname
      source_matchers:
      - "severity = critical"
      target_matchers:
      - "severity =~ warning|info"
    - equal:
      - namespace
      - alertname
      source_matchers:
      - "severity = warning"
      target_matchers:
      - "severity = info"
    receivers:
    - name: "null"
    - name: teams_aspecta
      msteams_configs:
        - send_resolved: true
          webhook_url_file: /etc/alertmanager/secrets/alertmanager-receivers/msteams_url
    - name: healthchecksio
      webhook_configs:
        - url_file: /etc/alertmanager/secrets/alertmanager-receivers/healthchecks_url
          send_resolved: false
    - name: atlassian_aspecta
      opsgenie_configs:
        - send_resolved: true
          api_key_file: /etc/alertmanager/secrets/alertmanager-receivers/opsgenie_key
          message: |
            [{{ `{{ "{{" }} .CommonLabels.customerName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.clusterName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.severity {{ "}}" }}` }}] -
            {{ `{{ "{{" }} range .Alerts {{ "}}" }}` }}
            {{ `{{ "{{" }} if .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} else if .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} else {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.message {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
            {{ `{{ "{{" }} end {{ "}}" }}` }}
          priority: '{{ `{{ "{{" }} if eq .CommonLabels.severity "critical" {{ "}}" }}` }}P1{{ `{{ "{{" }} else if eq .CommonLabels.severity "warning" {{ "}}" }}` }}P2{{ `{{ "{{" }} else if eq .CommonLabels.severity "info" {{ "}}" }}` }}P3{{ `{{ "{{" }} else {{ "}}" }}` }}P4{{ `{{ "{{" }} end {{ "}}" }}` }}'
          tags: |
            {{ `{{ "{{" }} with .CommonLabels.clusterName {{ "}}" }}` }}clusterName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.customerName {{ "}}" }}` }}customerName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.environment {{ "}}" }}` }}environment={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.location {{ "}}" }}` }}location={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.namespace {{ "}}" }}` }}namespace={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.severity {{ "}}" }}` }}severity={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.team {{ "}}" }}` }}team={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.vendor {{ "}}" }}` }}vendor={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.app {{ "}}" }}` }}app={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
    {{- if $hub.enabled }}
    - name: atlassian_aspecta_security
      opsgenie_configs:
        - send_resolved: false
          api_key_file: /etc/alertmanager/secrets/alertmanager-receivers/opsgenie_key_acs
          message: |
            [{{ `{{ "{{" }} .CommonLabels.customerName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.clusterName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.severity {{ "}}" }}` }}] -
            {{ `{{ "{{" }} range .Alerts {{ "}}" }}` }}
            {{ `{{ "{{" }} if .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} else if .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} else {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.message {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
            {{ `{{ "{{" }} end {{ "}}" }}` }}
          priority: '{{ `{{ "{{" }} if eq .CommonLabels.severity "critical" {{ "}}" }}` }}P1{{ `{{ "{{" }} else if eq .CommonLabels.severity "warning" {{ "}}" }}` }}P2{{ `{{ "{{" }} else if eq .CommonLabels.severity "info" {{ "}}" }}` }}P3{{ `{{ "{{" }} else {{ "}}" }}` }}P4{{ `{{ "{{" }} end {{ "}}" }}` }}'
          tags: |
            {{ `{{ "{{" }} with .CommonLabels.clusterName {{ "}}" }}` }}clusterName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.customerName {{ "}}" }}` }}customerName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.environment {{ "}}" }}` }}environment={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.location {{ "}}" }}` }}location={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.namespace {{ "}}" }}` }}namespace={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.severity {{ "}}" }}` }}severity={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.team {{ "}}" }}` }}team={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.vendor {{ "}}" }}` }}vendor={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.app {{ "}}" }}` }}app={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
    - name: atlassian_aspecta_logs
      opsgenie_configs:
        - send_resolved: false
          api_key_file: /etc/alertmanager/secrets/alertmanager-receivers/opsgenie_key_logs
          message: |
            [{{ `{{ "{{" }} .CommonLabels.customerName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.clusterName {{ "}}" }}` }}/{{ `{{ "{{" }} .CommonLabels.severity {{ "}}" }}` }}] -
            {{ `{{ "{{" }} range .Alerts {{ "}}" }}` }}
            {{ `{{ "{{" }} if .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.summary {{ "}}" }}` }}{{ `{{ "{{" }} else if .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.description {{ "}}" }}` }}{{ `{{ "{{" }} else {{ "}}" }}` }}{{ `{{ "{{" }} .Annotations.message {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
            {{ `{{ "{{" }} end {{ "}}" }}` }}
          priority: '{{ `{{ "{{" }} if eq .CommonLabels.severity "critical" {{ "}}" }}` }}P1{{ `{{ "{{" }} else if eq .CommonLabels.severity "warning" {{ "}}" }}` }}P2{{ `{{ "{{" }} else if eq .CommonLabels.severity "info" {{ "}}" }}` }}P3{{ `{{ "{{" }} else {{ "}}" }}` }}P4{{ `{{ "{{" }} end {{ "}}" }}` }}'
          tags: |
            {{ `{{ "{{" }} with .CommonLabels.clusterName {{ "}}" }}` }}clusterName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.customerName {{ "}}" }}` }}customerName={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.hostname {{ "}}" }}` }}hostname={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.environment {{ "}}" }}` }}environment={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.location {{ "}}" }}` }}location={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.namespace {{ "}}" }}` }}namespace={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.severity {{ "}}" }}` }}severity={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.team {{ "}}" }}` }}team={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.vendor {{ "}}" }}` }}vendor={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }},
            {{ `{{ "{{" }} with .CommonLabels.app {{ "}}" }}` }}app={{ `{{ "{{" }} . {{ "}}" }}` }}{{ `{{ "{{" }} end {{ "}}" }}` }}
    {{- end }}
    route:
      group_by:
      - namespace
      - alertname
      - severity
      group_interval: 5m
      group_wait: 30s
      receiver: teams_aspecta
      repeat_interval: 12h
      routes:
      - receiver: "null"
        matchers:
        - alertname =~ "CertificateIsAboutToExpire|CertificateApproachingExpiration"
        - name =~ "kubemacpool-service|result-server-cert-ocp4-cis-1-5"
      {{- if $hub.enabled }}
      - receiver: teams_aspecta
        continue: true
        matchers:
        - severity =~ "warning|critical"
        - alertname != Watchdog
      - receiver: atlassian_aspecta
        continue: true
        matchers:
        - severity =~ "warning|critical"
        - alertname != Watchdog
        - team != security
        - source != logs
      - receiver: atlassian_aspecta_security
        continue: true
        matchers:
        - severity =~ "warning|critical"
        - alertname != Watchdog
        - team = security
        group_by:
        - namespace
        - alertname
        - severity
        - clusterName
        - acs_alert_id
      - receiver: atlassian_aspecta_logs
        continue: true
        matchers:
        - severity =~ "warning|critical"
        - alertname != Watchdog
        - source = logs
        group_by:
        - namespace
        - alertname
        - severity
        - clusterName
        - hostname
        - msgid
      {{- else }}
      - receiver: atlassian_aspecta
        continue: true
        matchers:
        - severity =~ "warning|critical"
        - alertname != Watchdog
        - vendor = "aspecta"
      {{- end }}
      - receiver: healthchecksio
        matchers:
        - alertname = Watchdog
        group_wait: 0s
        group_interval: 60s
        repeat_interval: 60s
      - receiver: "null"
        matchers:
        - severity =~ "info|none"
      - receiver: "null"
        matchers:
        - vendor != "aspecta"
{{- end }}
