---
apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: {{ default "distributed-tracing" .Values.uiPlugin.name | quote }}
  labels:
{{- include "tempo-operator.labels" . | nindent 4 }}
spec:
  type: {{ default "DistributedTracing" .Values.uiPlugin.type | quote }}
