apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "crossplane-helm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crossplane-helm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: crossplane
  podMetricsEndpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
