---
# TESTING apc.namespace.test - change occurence to apc.namespace.type. This is only for testing of the kyverno clusterpolicy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-tempostack-tenants
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    policies.kyverno.io/title: Update TempoStack tenants on namespace create
    policies.kyverno.io/category: gitops
    policies.kyverno.io/subject: Sync TempoStack tenants with namespaces
    policies.kyverno.io/minversion: 1.13.0
  labels:
{{- include "tempo-stack.labels" . | nindent 4 }}
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
    - name: add-tenant-to-tempostack
      match:
        any:
          - resources:
              kinds:
                - Namespace
      exclude:
        any:
          - resources:
              namespaces:
                - "kube-*"
                - "kyverno"
                - "openshift-*"
      preconditions:
        all:
          - key: {{`"{{ request.object.metadata.labels.\"apc.namespace.test\" }}"`}}
            operator: Equals
            value: application
      mutate:
        targets:
          - apiVersion: tempo.grafana.com/v1alpha1
            kind: TempoStack
            name: {{ default "apc-tempo-stack" .Values.tempoStack.name | quote }}
            namespace: {{ .Release.Namespace | quote }}
        patchStrategicMerge:
          spec:
            tenants:
              authentication:
                # The +(...) anchor adds the item to the list if it doesn't already exist
                - +(tenantName): {{`"{{ request.object.metadata.name }}"`}}
                  tenantId: {{`"{{ request.object.metadata.name }}"`}}