---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ default "apc-tempo-stack" .Values.tempoStack.name }}-generate-tenant-clusterrole-read
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    policies.kyverno.io/title: Generate ClusterRoles to read  TempoStack tenants for  namespace
    policies.kyverno.io/category: gitops
    policies.kyverno.io/subject: Generate ClusterRoles for application namespaces
    policies.kyverno.io/minversion: 1.13.0
  labels:
{{- include "tempo-stack.labels" . | nindent 4 }}
spec:
  background: true
  validationFailureAction: Audit
  rules:
    - name: generate-clusterrole-reader-for-application-namespace
      match:
        any:
        - resources:
            kinds:
            - Namespace
            selector:
              matchLabels:
                {{ .Values.namespaceSelector.key }}: {{ .Values.namespaceSelector.value }}
      generate:
        generateExisting: true
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        name: {{ default "apc-tempo-stack" .Values.tempoStack.name }}-reader-{{`{{request.object.metadata.name}}`}}
        synchronize: true
        data:
          metadata:
            labels:
              generated-by: generate-reader-clusterrole-for-application-namespace
          rules:
          - apiGroups:
              - tempo.grafana.com
            resources:
              - {{`"{{request.object.metadata.name}}"`}}
            resourceNames:
              - traces
            verbs:
              - get