---
# TESTING apc.namespace.test - change occurence to apc.namespace.type. This is only for testing of the kyverno clusterpolicy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ default "apc-tempo-stack" .Values.tempoStack.name }}-generate-tenant-clusterrole-write
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    policies.kyverno.io/title: Generate ClusterRoles to write into TempoStack tenants for  namespace
    policies.kyverno.io/category: gitops
    policies.kyverno.io/subject: Generate ClusterRoles for application namespaces
    policies.kyverno.io/minversion: 1.13.0
  labels:
{{- include "tempo-stack.labels" . | nindent 4 }}
spec:
  background: true
  validationFailureAction: Audit
  rules:
    - name: generate-clusterrole-writer-for-application-namespace
      match:
        any:
        - resources:
            kinds:
            - Namespace
            selector:
              matchLabels:
                {{ .Values.namespaceSelector.key }}: {{ .Values.namespaceSelector.value }}
      generate:
        generateExisting: true
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        name: {{ default "apc-tempo-stack" .Values.tempoStack.name }}-writer-{{`{{request.object.metadata.name}}`}}"
        synchronize: true
        data:
          metadata:
            labels:
              generated-by: generate-writer-clusterrole-for-application-namespace
              {{- if .Values.otelCollector.role.aggregation.enabled }}
              {{ .Values.otelCollector.role.aggregation.clusterRoleName }}: "true"
              {{- end }}
          rules:
            - apiGroups:
                - tempo.grafana.com
              resources:
                - {{`"{{request.object.metadata.name}}"`}}
              resourceNames:
                - traces
              verbs:
                - 'create'