---
# TESTING apc.namespace.test - change occurence to apc.namespace.type. This is only for testing of the kyverno clusterpolicy
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: cleanup-tempostack-tenants
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    policies.kyverno.io/title: Update TempoStack tenants on namespace delete
    policies.kyverno.io/category: gitops
    policies.kyverno.io/subject: Cleanup TempoStack tenants
    policies.kyverno.io/minversion: 1.13.0
  labels:
{{- include "tempo-stack.labels" . | nindent 4 }}
spec:
  mutateExistingOnPolicyUpdate: false 
  rules:
    - name: remove-tenant-from-tempostack-on-namespace-delete
      match:
        any:
          - resources:
              kinds:
                - Namespace
              operations:
                - DELETE
      exclude:
        any:
          - resources:
              namespaces:
                - "kube-*"
                - "kyverno"
                - "openshift-*"
      context:
        - name: tenant_exists
          apiCall:
            urlPath: /apis/tempo.grafana.com/v1alpha1/namespaces/{{ .Release.Namespace }}/tempostacks/{{ default "apc-tempo-stack" .Values.tempoStack.name }}
            jmesPath: "contains((spec.tenants.authentication[].tenantName || `[]`), '{{ `{{` }} request.oldObject.metadata.name {{ `}}` }}')"

      preconditions:
        all:
          - key: {{`"{{ request.oldObject.metadata.labels.\"apc.namespace.test\" || '' }}"`}}
            operator: Equals
            value: application
          - key: {{`"{{ tenant_exists }}"`}}
            operator: Equals
            value: true
      mutate:
        targets:
          - apiVersion: tempo.grafana.com/v1alpha1
            kind: TempoStack
            name: {{ default "apc-tempo-stack" .Values.tempoStack.name | quote }}
            namespace: {{ default .Release.Namespace .Values.tempoStack.namespace | quote }}
        patchStrategicMerge:
          spec:
            tenants:
              authentication:
                - tenantName: {{`"{{ request.oldObject.metadata.name }}"`}}
                  $patch: delete
