---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-cluster-observability-operator
  namespace: apc-observability
  labels:
{{- include "tempo-stack.labels" . | nindent 4 }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: openshift-cluster-observability-operator
  podSelector: {}
  policyTypes:
  - Ingress
