apiVersion: v2
name: custom-metrics-autoscaler-config
description: KedaController custom resource to configure KEDA for the OpenShift Custom Metrics Autoscaler Operator
type: application
version: 1.0.0
appVersion: "2.19.0-3"
