{{- $enabled := .Values.externalSecret.enabled }}
{{- if kindIs "invalid" $enabled }}
  {{- $enabled = ne (include "apc-global-overrides.clusterIsHub" .) "true" }}
{{- end }}
{{- if $enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "logging-instance.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging-instance.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  target:
    name: {{ include "logging-instance.fullname" . }}
    creationPolicy: Owner
  data:
    - secretKey: TOKEN
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/openshift-logging/hub-spoke-logforward
        property: TOKEN
{{- end }}
