{{- if eq (include "apc-global-overrides.clusterIsHub" .) "true" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spoke-logforward
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "logging-instance.labels" . | nindent 4 }}
{{- end }}
