apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
  labels:
    {{- include "logging-instance.labels" . | nindent 4 }}
spec:
  type: Logging
  logging:
    lokiStack:
      name: {{ include "logging-instance.lokistackName" . }}
    # Workaround for issue https://access.redhat.com/solutions/6998442
    timeout: {{ .Values.uiplugin.timeout | default "120s" }}
