apiVersion: v2
name: coo-operator
description: A Helm chart to install Cluster Observability Operator using ACM OperatorPolicy
type: application
version: 1.0.0
appVersion: "1.2.2"
dependencies:
  - name: acm-operatorpolicy
    version: "1.3.0"
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
