acm-operatorpolicy:
  subscription:
    channel: "stable"
    name: cluster-observability-operator
    namespace: openshift-cluster-observability-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: cluster-observability-operator.v1.2.2
  operatorGroup:
    name: openshift-cluster-observability-operator
    namespace: openshift-cluster-observability-operator
    targetNamespaces:
      - openshift-cluster-observability-operator
  upgradeApproval: None
  versions:
    - cluster-observability-operator.v1.2.2
