nameOverride: ""
fullnameOverride: ""

replicas: 2

resources:
  limits:
    cpu: 500m
    memory: 300Mi
  requests:
    cpu: 50m
    memory: 100Mi

functions:
  - name: function-debug
    package: xpkg.upbound.io/modulo2/function-debug:v0.1.0
  - name: function-environment-configs
    package: xpkg.upbound.io/crossplane-contrib/function-environment-configs:v0.6.0
