nameOverride: ""
fullnameOverride: ""

replicas: 2

resources:
  limits:
    cpu: 500m
    memory: 300Mi
  requests:
    cpu: 50m
    memory: 100Mi

functions:
  - name: auto-ready
    package: xpkg.crossplane.io/crossplane-contrib/function-auto-ready:v0.5.2
  - name: go-templating
    package: xpkg.crossplane.io/crossplane-contrib/function-go-templating:v0.11.1
