apiVersion: vault.vault.upbound.io/v1alpha1
kind: Audit
metadata:
  name: audit
  annotations:
    crossplane.io/external-name: file
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  deletionPolicy: Orphan
  managementPolicy: ["Create", "Update", "Observe", "LateInitialize"]
  forProvider:
    options:
      file_path: stdout
    type: file
  providerConfigRef:
    name: {{ include "apc-global-overrides.crossplaneKubeVaultProviderConfigName" $ }}
