{{- range $authMethod, $authData := .Values.authMethods }}
{{- range $data := $authData }}
{{- if $data.enable }}
apiVersion: auth.vault.upbound.io/v1alpha1
kind: Backend
metadata:
  name: {{ $data.name }}-auth
  annotations:
    crossplane.io/external-name: {{ $data.name }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  deletionPolicy: Orphan
  forProvider:
    type: {{ $authMethod}}
    path: {{ $data.name }}
    {{- if $data.tune }}
    tune:
    {{- $data.tune | toYaml | nindent 6 }}
    {{- end }}
  providerConfigRef:
    name: {{ include "apc-global-overrides.crossplaneKubeVaultProviderConfigName" $ }}
---
{{- end }}
{{- end }}
{{- end }}
