{{- range $engine, $engineData := .Values.secretEngines }}
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Mount
metadata:
  name: {{ $engine }}-secret-engine
  annotations:
    crossplane.io/external-name: {{ $engine }}
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  deletionPolicy: Orphan
  managementPolicy: ["Create", "Update", "Observe", "LateInitialize"]
  forProvider:
    path: {{ $engine }}
    type: {{ $engineData.type }}
  providerConfigRef:
    name: {{ include "apc-global-overrides.crossplaneKubeVaultProviderConfigName" $ }}
---
{{- end }}
