{{- range $policy, $policyData := .Values.policies.customPolicies }}
apiVersion: vault.vault.upbound.io/v1alpha1
kind: Policy
metadata:
  name: {{ $policy }}-policy
  annotations:
    crossplane.io/external-name: {{ $policy }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  forProvider:
    name: {{ $policy }}
    policy: | 
      {{- $policyData.rules | nindent 6 }}
  providerConfigRef:
    name: {{ include "apc-global-overrides.crossplaneKubeVaultProviderConfigName" $ }}
---
{{- end }}
