{{- $roleDefaultSettings := .Values.pkiIssuer.pkiRoles.defaultSettings  }}
{{- $defaultDomains := (include "vault-config.defaultAllowedDomains" .) }}
{{- range $role, $roleData := .Values.pkiIssuer.pkiRoles.roles }}
{{- $mergedSettings := mergeOverwrite (deepCopy $roleDefaultSettings) ($roleData.settings | default dict) }}

{{- $allowedDomains := "" }}
{{- if $roleData.allowedDomains }}
  {{- $allowedDomains = $roleData.allowedDomains | toYaml }}
{{- else }}
  {{- $allowedDomains = $defaultDomains }}
{{- end }}

apiVersion: pki.vault.upbound.io/v1alpha1
kind: SecretBackendRole
metadata:
  name: {{ $roleData.name | default (printf "%s.%s" (include "apc-global-overrides.clusterName" $) (include "apc-global-overrides.clusterAppsDomain" $)) }}
  annotations:
    crossplane.io/external-name: {{ $roleData.backend }}/roles/{{ $roleData.name | default (printf "%s.%s" (include "apc-global-overrides.clusterName" $) (include "apc-global-overrides.clusterAppsDomain" $)) }}
  labels:
    {{- include "vault-config.labels" $ | nindent 4 }}
spec:
  forProvider:
    name: {{ $roleData.name | default (printf "%s.%s" (include "apc-global-overrides.clusterName" $) (include "apc-global-overrides.clusterAppsDomain" $)) }}
    backend: {{ $roleData.backend }}
    issuerRef: {{ $.Values.pkiIssuer.issuerName | default "default" }}
    {{- $mergedSettings | toYaml | nindent 4 }}
    allowedDomains:
    {{- $allowedDomains | nindent 6 }}
  providerConfigRef:
    name: {{ include "apc-global-overrides.crossplaneKubeVaultProviderConfigName" $ }}
---
{{- end }}
