{{- if and (.Values.pkiIssuers.default.createIssuer) (not .Values.pkiIssuers.existing.issuerName) }}
apiVersion: pki.vault.upbound.io/v1alpha1
kind: SecretBackendConfigCA
metadata:
  name: default-ca-issuer
  annotations:
    crossplane.io/external-name: {{ .Values.pkiIssuers.default.pkiName }}
    {{- include "vault-config.labels" . | nindent 4 }}
spec:
  deletionPolicy: Orphan
  managementPolicy: ["Create","Update", "Observe", "LateInitialize"]
  forProvider:
    backend: {{ .Values.pkiIssuers.default.pkiName }}
    pemBundleSecretRef:
      name: issuer-ca-pem-bundle
      namespace: default
      key: pemBundle
  providerConfigRef:
    name: {{ include "apc-global-overrides.crossplaneKubeVaultProviderConfigName" $ }}
{{- end }}
