apiVersion: v2
name: quay-config
description: APC Quay Registry
type: application
version: 0.1.0
#appVersion: "3.15.1"
dependencies:
  - name: apc-global-overrides
    version: 1.8.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
