apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "sql-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sql-server.labels" . | nindent 4 }}
spec:
  refreshInterval: "0"
  #refreshPolicy it is not supported for external-secrets v 0.11
  #refreshPolicy: "CreatedOnce"
  target:
    name: {{ include "sql-server.fullname" . }}
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "sql-server.labels" . | nindent 10 }}
      data:
        mssql_sa_password : "{{ `{{ .password }}` }}" 
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: Password
        name: {{ include "sql-server.fullname" . }}
