apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: {{ include "sql-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "sql-server.labels" . | nindent 4 }}
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "!#$%&'*+-.^_`|~"
  noUpper: false
  allowRepeat: false
