acm-operatorpolicy:
  subscription:
    channel: stable
    name: openshift-custom-metrics-autoscaler-operator
    namespace: openshift-keda
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: custom-metrics-autoscaler.v2.19.0-3

  upgradeApproval: Automatic
  versions:
    - custom-metrics-autoscaler.v2.19.0-3

  operatorGroup:
    name: openshift-keda
    namespace: openshift-keda
    targetNamespaces:
      - openshift-keda
