apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pullsecret-{{ include "cluster-infraenv.infraEnvName" . }}
  namespace: {{ include "cluster-infraenv.infraEnvName" . }}
  labels:
    {{- include "cluster-infraenv.labels" . | nindent 4 }}
    agent-install.openshift.io/watch: 'true'
    cluster.open-cluster-management.io/backup: 'true'
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: pullsecret-{{ include "cluster-infraenv.infraEnvName" . }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{`{{ .pullsecret | toString }}`}}"
  data:
    - secretKey: pullsecret
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/infraenv/{{ include "cluster-infraenv.infraEnvName" . }}/pullSecret
        property: .dockerconfigjson
