{{- range .Values.nmStateConfigs | required "nmStateConfigs must be set" }}
---
apiVersion: agent-install.openshift.io/v1beta1
kind: NMStateConfig
metadata:
  name: {{ .name }}
  namespace: {{ include "cluster-infraenv.infraEnvName" $ }}
  labels:
    {{- include "cluster-infraenv.labels" $ | nindent 4 }}
    infraenvs.agent-install.openshift.io: {{ include "cluster-infraenv.infraEnvName" $ }}
spec:
  config:
    {{- toYaml .config | nindent 4 }}
  interfaces:
    {{- range .interfaces }}
    - macAddress: {{ .macAddress }}
      name: {{ .name }}
    {{- end }}
{{- end }}
