{{- $clusterName := include "cluster-instance-hcp.clusterName" . }}
{{- $rootDomain := include "apc-global-overrides.require-clusterRootDomain" . }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kube-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
spec:
  secretName: kube-apiserver-cert
  issuerRef:
    name: {{ include "apc-global-overrides.require-certManagerDefaultClusterIssuer" . }}
    kind: ClusterIssuer
  dnsNames:
    - api.{{ $clusterName }}.{{ $rootDomain }}
    - oauth.{{ $clusterName }}.{{ $rootDomain }}
