{{- if and (include "apc-global-overrides.caCertificatesBundle" .) ((((include "apc-global-overrides.ldapIntegration" .) | fromYaml).ldap).attributes).url }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: bastion-ldap-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
data:
  ca.crt: |
    {{- include "apc-global-overrides.caCertificatesBundle" . | nindent 4 }}
{{- end }}
