{{- $chronyConf := "" -}}
{{- range .Values.ntpServers -}}
  {{- $chronyConf = printf "%sserver %s iburst\n" $chronyConf . -}}
{{- end -}}
{{- $chronyConf = printf "%sdriftfile /var/lib/chrony/drift\nmakestep 1.0 3\nrtcsync\nlogdir /var/log/chrony\n" $chronyConf -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: machineconfig-chrony
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: MachineConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: worker
      name: 99-worker-chrony
    spec:
      config:
        ignition:
          version: 3.4.0
        storage:
          files:
            - contents:
                compression: ''
                source: 'data:text/plain;charset=utf-8;base64,{{ $chronyConf | b64enc }}'
              mode: 420
              overwrite: true
              path: /etc/chrony.conf
