apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeletconfig-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
data:
  config: |
    apiVersion: machineconfiguration.openshift.io/v1
    kind: KubeletConfig
    metadata:
      labels:
        machineconfiguration.openshift.io/role: worker
      name: kubeletconfig-worker
    spec:
      kubeletConfig:
        containerLogMaxFiles: 5
        containerLogMaxSize: 20Mi
        podsPerCore: 0
        maxPods: 350
        systemReserved:
          cpu: 800m
          memory: 4Gi
          ephemeral-storage: 3Gi
