{{- $imageProxyHost := include "apc-global-overrides.imageProxyHost" . }}
{{- $caCertificatesBundle := include "apc-global-overrides.caCertificatesBundle" . }}
{{- if $caCertificatesBundle and $imageProxyHost }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-ca-bundle
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
data:
  {{ $imageProxyHost }}..443: |
    {{- $caCertificatesBundle | nindent 4 }}
{{- end }}
