{{- if .Values.apiServerCert.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: kube-apiserver-cert
    creationPolicy: Owner
    template:
      type: kubernetes.io/tls
  data:
    - secretKey: tls.crt
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ required "apiServerCert.vaultKey is required when apiServerCert.enabled" .Values.apiServerCert.vaultKey }}
        property: {{ .Values.apiServerCert.vaultTLSCrt }}
    - secretKey: tls.key
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ .Values.apiServerCert.vaultKey }}
        property: {{ .Values.apiServerCert.vaultTLSKey }}
{{- end }}
