{{- $clusterName := include "cluster-instance-hcp.clusterName" . }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pullsecret-cluster-{{ $clusterName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: pullsecret-cluster-{{ $clusterName }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{`{{ .pullsecret | toString }}`}}"
  data:
    - secretKey: pullsecret
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/hcp/{{ $clusterName }}/pullSecret
        property: .dockerconfigjson
