{{- if .Values.ldapIntegration.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bastion-ldap-bind-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: bastion-ldap-bind-secret
    creationPolicy: Owner
  data:
    - secretKey: bindPassword
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ required "ldapIntegration.vaultKey is required when ldapIntegration.enabled" .Values.ldapIntegration.vaultKey }}
        property: {{ .Values.ldapIntegration.vaultProperty }}
{{- end }}
