apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sshkey-cluster-{{ include "cluster-instance-hcp.clusterName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ include "apc-global-overrides.require-ESODefaultClusterSecretStore" . }}
    kind: ClusterSecretStore
  target:
    name: sshkey-cluster-{{ include "cluster-instance-hcp.clusterName" . }}
    creationPolicy: Owner
  data:
    - secretKey: id_rsa.pub
      remoteRef:
        key: {{ include "apc-global-overrides.require-vaultKVmountPlatform" . }}/{{ include "apc-global-overrides.require-environmentShort" . }}/{{ required "vault.sshKeyKey is required" .Values.vault.sshKeyKey }}
        property: {{ .Values.vault.sshKeyProperty }}
