{{- $clusterName := include "cluster-instance-hcp.clusterName" . }}
{{- $clusterSet := include "cluster-instance-hcp.clusterSet" . }}
{{- $rootDomain := include "apc-global-overrides.require-clusterRootDomain" . }}
{{- $proxy := include "apc-global-overrides.proxy" . }}
{{- $caCertificatesBundle := include "apc-global-overrides.caCertificatesBundle" . }}
{{- $imageProxyHost := include "apc-global-overrides.imageProxyHost" . }}
{{- $adIntegration := (include "apc-global-overrides.adIntegration" .) | fromYaml }}
{{- $ldapIntegration := (include "apc-global-overrides.ldapIntegration" .) | fromYaml }}
apiVersion: hypershift.openshift.io/v1beta1
kind: HostedCluster
metadata:
  name: {{ $clusterName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
    cluster.open-cluster-management.io/clusterset: {{ $clusterSet | quote }}
spec:
  {{- if $caCertificatesBundle }}
  additionalTrustBundle:
    name: user-ca-bundle
  {{- end }}
  channel: eus-4.18
  configuration:
    apiServer:
      audit:
        profile: Default
      servingCerts:
        namedCertificates:
          - names:
              - api.{{ $clusterName }}.{{ $rootDomain }}
              - oauth.{{ $clusterName }}.{{ $rootDomain }}
            servingCertificate:
              name: kube-apiserver-cert
    {{- if $imageProxyHost }}
    image:
      additionalTrustedCA:
        name: registry-ca-bundle
    {{- end }}
    {{- if or $adIntegration $ldapIntegration }}
    oauth:
      identityProviders:
        {{- if $adIntegration }}
        - {{ $adIntegration | toYaml | indent 10 | trim }}
        {{- end }}
        {{- if $ldapIntegration }}
        {{- end }}
        {{- if $ldapIntegration }}
        - {{ $ldapIntegration | toYaml | indent 10 | trim}}
        {{- end }}
    {{- end }}
    {{- if $proxy }}
    proxy:
      httpProxy: {{ $proxy | quote }}
      httpsProxy: {{ $proxy | quote }}
      noProxy: {{ include "apc-global-overrides.noProxy" . | quote }}
      trustedCA:
        name: user-ca-bundle
    {{- end }}
  imageContentSources:
    {{- range (include "apc-global-overrides.imageProxySources" . | fromYamlArray) }}
    - mirrors:
        - {{ $imageProxyHost }}/{{ . }}
      source: {{ . }}
    {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  etcd:
    managed:
      storage:
        persistentVolume:
          size: {{ .Values.etcd.storageSize }}
          storageClassName: {{ .Values.etcd.storageClassName }}
        type: PersistentVolume
    managementType: Managed
  release:
    image: {{ .Values.releaseImage }}
  pullSecret:
    name: pullsecret-cluster-{{ $clusterName }}
  {{- if include "apc-global-overrides.sshAuthorizedKeys" . }}
  sshKey:
    name: sshkey-cluster-{{ $clusterName }}
  {{- end }}
  networking:
    clusterNetwork:
      - cidr: {{ .Values.networking.clusterCIDR }}
        hostPrefix: {{ .Values.networking.clusterHostPrefix }}
    networkType: OVNKubernetes
    serviceNetwork:
      - cidr: {{ .Values.networking.serviceCIDR }}

  controllerAvailabilityPolicy: HighlyAvailable
  infrastructureAvailabilityPolicy: HighlyAvailable
  olmCatalogPlacement: management
  platform:
    type: Agent
    agent:
      agentNamespace: {{ include "cluster-instance-hcp.infrastructureNamespace" . }}
  infraID: {{ $clusterName }}
  dns:
    baseDomain: {{ $rootDomain }}
  services:
    - service: APIServer
      servicePublishingStrategy:
        type: LoadBalancer
    - service: OAuthServer
      servicePublishingStrategy:
        type: NodePort
        nodePort:
          address: oauth.{{ $clusterName }}.{{ $rootDomain }}
          port: {{ .Values.services.oauthPort | required ".services.oauthPort must be set" }}
    - service: Konnectivity
      servicePublishingStrategy:
        type: NodePort
        nodePort:
          address: konnectivity.{{ $clusterName }}.{{ $rootDomain }}
          port: {{ .Values.services.konnectivityPort | required ".services.konnectivityPort must be set" }}
    - service: Ignition
      servicePublishingStrategy:
        type: NodePort
        nodePort:
          address: ignition.{{ $clusterName }}.{{ $rootDomain }}
          port: {{ .Values.services.ignitionPort | required ".services.ignitionPort must be set" }}
    - service: OIDC
      servicePublishingStrategy:
        type: NodePort
        nodePort:
          address: oidc.{{ $clusterName }}.{{ $rootDomain }}
          port: {{ .Values.services.oidcPort | required ".services.oidcPort must be set"}}
