{{- if include "apc-global-overrides.sshAuthorizedKeys" . }}
{{- $clusterName := include "cluster-instance-hcp.clusterName" . }}
apiVersion: v1
kind: Secret
metadata:
  name: sshkey-cluster-{{ $clusterName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cluster-instance-hcp.labels" . | nindent 4 }}
stringData:
  id_rsa.pub: {{ include "apc-global-overrides.sshAuthorizedKeys" . | quote }}
{{- end }}
