apiVersion: v2
name: crossplane-vault-provider
description: A Helm chart to deploy Crossplane Vault provider
type: application
version: 1.5.0
appVersion: "v2.2.2"

dependencies:
  - name: apc-global-overrides
    version: 1.5.0
    repository: https://raw.githubusercontent.com/gr8it/charts-openshift/refs/heads/main/
