nameOverride: ""
fullnameOverride: ""

providerPackage: xpkg.upbound.io/upbound/provider-vault:v2.2.2

global:
  apc:
    caCertificates:
      example.crt: |
        -----BEGIN CERTIFICATE-----
        aaa
        -----END CERTIFICATE-----
      example2.crt: |
        -----BEGIN CERTIFICATE-----
        bbb
        -----END CERTIFICATE-----
