nameOverride: ""
fullnameOverride: ""

providerPackage: xpkg.upbound.io/upbound/provider-vault:v2.2.2

# Global overrides
# global:
#   apc:
#     caCertificates:
#       ca.crt: |
#         -----BEGIN CERTIFICATE-----
#         ...
#         -----END CERTIFICATE-----
