nameOverride: ""
fullnameOverride: ""

providerPackage: xpkg.upbound.io/upbound/provider-vault:v2.2.2

resources:
  limits:
    cpu: 500m
    memory: 600Mi
  requests:
    cpu: 50m
    memory: 200Mi

# Global overrides
# global:
#   apc:
#     caCertificates:
#       ca.crt: |
#         -----BEGIN CERTIFICATE-----
#         ...
#         -----END CERTIFICATE-----
