apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "veeam-exporter.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "veeam-exporter.labels" . | nindent 4 }}
data:
  CONFIG.ps1: |
    # C:\Scripts\CONFIG.ps1
    $Config = @{
        GROUP = '{{ .Values.exporterConfig.group }}'
        BASE_URL = '{{ .Values.exporterConfig.pushgatewayUrl }}'
        SERVER = $env:COMPUTERNAME
        JobRunVisualizationWindowSeconds = '{{ .Values.exporterConfig.jobRunVisualizationWindowSeconds }}'
    }
